{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 590804,
          "sha512": "a80991cd3a259f14ad78ec4c5f56ce7b92786801a5313288d7f0eb6efe26f6852608348c5db4f6b00b49d24e0fa2abd34f470525fa0b8d4f946a4c15ccc0f6b4",
          "sha256": "09f37a01b1bebae954cb92e93141a32b59603a7a66deda7effafe0453d036e99",
          "sha1": "ec9b43ebf32043ded1bfcd0c631d1085fa4b9dd1",
          "md5": "e76be6c8537bb48e2acd7d125a8fd2b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 590804,
          "sha512": "a80991cd3a259f14ad78ec4c5f56ce7b92786801a5313288d7f0eb6efe26f6852608348c5db4f6b00b49d24e0fa2abd34f470525fa0b8d4f946a4c15ccc0f6b4",
          "sha256": "09f37a01b1bebae954cb92e93141a32b59603a7a66deda7effafe0453d036e99",
          "sha1": "ec9b43ebf32043ded1bfcd0c631d1085fa4b9dd1",
          "md5": "e76be6c8537bb48e2acd7d125a8fd2b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.0.0-sources.jar",
          "url": "yieldlove-8.0.0-sources.jar",
          "size": 205808,
          "sha512": "bc97566a64609e9e4502c4f5d406dee3e640123c0fb226d540aed7a6b1421ee75b4bbf821930b9a09f402bbf807a396207594290a671b373320539adfd397b87",
          "sha256": "ed5e089d5504247af156b0c48a99e164bb36ff035dee0cb662d48b8caa8bad85",
          "sha1": "d29e3cc2d059ce363b19cf538d9f0859fab10d03",
          "md5": "72cdcba16885deea73ef52be7ebe4f87"
        }
      ]
    }
  ]
}
