{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 590812,
          "sha512": "b18a01f21cf5a39f26a08d5c3c009a40e469dbe6a1103948e3cc2082f9ca066f1579a042745a0acd3b71ae2608ab545b063ef65e162f18c98d3dd8e795cf2d56",
          "sha256": "54d12cfc4565ae41ac65b075c29ab8156a9f262a1f838f6a3ca29a5b52053515",
          "sha1": "3488ba41658e4a8838f53bd73c35b72a623318d4",
          "md5": "81cca378de65e12cd0de361ae052daeb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 590812,
          "sha512": "b18a01f21cf5a39f26a08d5c3c009a40e469dbe6a1103948e3cc2082f9ca066f1579a042745a0acd3b71ae2608ab545b063ef65e162f18c98d3dd8e795cf2d56",
          "sha256": "54d12cfc4565ae41ac65b075c29ab8156a9f262a1f838f6a3ca29a5b52053515",
          "sha1": "3488ba41658e4a8838f53bd73c35b72a623318d4",
          "md5": "81cca378de65e12cd0de361ae052daeb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.0.0-sources.jar",
          "url": "yieldlove-8.0.0-sources.jar",
          "size": 205808,
          "sha512": "771b6512cca4557e02de4fa8267e460bf91238c01892ea4bfa1dba49e3c8b41117d348af239fdc09f29d9798cde2d26d0d71a8b81770faa4f0f7896ccb3d3b7e",
          "sha256": "dffc6c0c84a004dfeb2381e3ca27db828cd8c5be23bd7a776ab9b7580951a4e9",
          "sha1": "07a0c0cf357614a8ac3f9b31ba1877a0ad107810",
          "md5": "4d701749caa013ecd1c28f57f4202535"
        }
      ]
    }
  ]
}
