{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 591189,
          "sha512": "9fbd5f0e1a7fd460cb1456b7bdbce51e4fa0e87f6d5cfe8c5e1a55933be8b92f6e625b86e4ff74d3687a8cde4fb4cf5579f41716a12527ce4406183f30228a77",
          "sha256": "76ac7cfcce473c4701e37b6f310cdc3548d70a863d8ca5ab6a88d2f9ebf6e3f0",
          "sha1": "cdbe5d5e205a4404e3de57ea4560e1ebdb9b8556",
          "md5": "65778cbc00a76cbf6ccea5eb3021854f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.0.0.aar",
          "url": "yieldlove-8.0.0.aar",
          "size": 591189,
          "sha512": "9fbd5f0e1a7fd460cb1456b7bdbce51e4fa0e87f6d5cfe8c5e1a55933be8b92f6e625b86e4ff74d3687a8cde4fb4cf5579f41716a12527ce4406183f30228a77",
          "sha256": "76ac7cfcce473c4701e37b6f310cdc3548d70a863d8ca5ab6a88d2f9ebf6e3f0",
          "sha1": "cdbe5d5e205a4404e3de57ea4560e1ebdb9b8556",
          "md5": "65778cbc00a76cbf6ccea5eb3021854f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.0.0-sources.jar",
          "url": "yieldlove-8.0.0-sources.jar",
          "size": 205895,
          "sha512": "f11d3689b1f9046b0b61166a42bab7de6059f208b35dbd305d2c33909d4f62d431da55ae2ba5470cd673a488221483dd04ea61f3d4b6d48ac647d1fa151c584f",
          "sha256": "7fa04cc126fa2e7a399b7e2df41a94fee68b732c8a44cf869ed03a66bc69e2a6",
          "sha1": "7a5bd07821e9b500162582fda9e7100007c70433",
          "md5": "ef00bcc03d195e08d7e88b7d4e8ef668"
        }
      ]
    }
  ]
}
