{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.1.aar",
          "url": "confiant-8.2.1.aar",
          "size": 6592,
          "sha512": "60f322b207a631d92a7c03b20d6bcbfa052dac700803f5da2509eda8c9930f92738b42d9e5c7298bfda8d3aa479950d63d822120074dd6a9be0ac100547d4bf9",
          "sha256": "71afef98b4e18380feb75f8b7a97f562c943b015bab786074f2e603f3317edff",
          "sha1": "99588a3f074671adf0e3647fdce9706387e2037f",
          "md5": "d8b5bb2b187f90357d1875d7cd77fcb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.1.aar",
          "url": "confiant-8.2.1.aar",
          "size": 6592,
          "sha512": "60f322b207a631d92a7c03b20d6bcbfa052dac700803f5da2509eda8c9930f92738b42d9e5c7298bfda8d3aa479950d63d822120074dd6a9be0ac100547d4bf9",
          "sha256": "71afef98b4e18380feb75f8b7a97f562c943b015bab786074f2e603f3317edff",
          "sha1": "99588a3f074671adf0e3647fdce9706387e2037f",
          "md5": "d8b5bb2b187f90357d1875d7cd77fcb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.2.1-sources.jar",
          "url": "confiant-8.2.1-sources.jar",
          "size": 3245,
          "sha512": "d3e28174732c0626cd3773fa3f6079c31e4f119e32cef921d97040835490e8d85a82bd341684406b16d4b86ba763cf861b5fde8e5294b4edbdc480afbaa29f5e",
          "sha256": "a3a90104a374de1055715d47e10d8dce4d667db48cf6cb4669d20b926f5c0a26",
          "sha1": "dad072c1851b99222b189290caed36a949399d13",
          "md5": "0d1ba361aedebc56b3b37ceda67a67bb"
        }
      ]
    }
  ]
}
