{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439681,
          "sha512": "10d09d8fad9b30a27f205c44fdfefa8625e62c54632d7134320d5197123f08bacb48f94949fa1754af3b00d04da5cac3a2018b645fd79a1753352d7acfc1fbdb",
          "sha256": "8f371beffea7a211d7eab970dca033bc2e4191cf895c09cfe375e76295170fe6",
          "sha1": "f2014d415efbe09dc5b9b61cfbf4fb7c417232c8",
          "md5": "16ba68d47ac1201da9d2d242ff1e32ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439681,
          "sha512": "10d09d8fad9b30a27f205c44fdfefa8625e62c54632d7134320d5197123f08bacb48f94949fa1754af3b00d04da5cac3a2018b645fd79a1753352d7acfc1fbdb",
          "sha256": "8f371beffea7a211d7eab970dca033bc2e4191cf895c09cfe375e76295170fe6",
          "sha1": "f2014d415efbe09dc5b9b61cfbf4fb7c417232c8",
          "md5": "16ba68d47ac1201da9d2d242ff1e32ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-7.2.0-sources.jar",
          "url": "yieldlove-7.2.0-sources.jar",
          "size": 201175,
          "sha512": "1661394628401a11af46960de6b8bce40f14e3ed7c19416ea8f715f97c94c70e7b8192e05690d717b8c5f99ef47681f22e750b108d434e0e4164c490f712dcad",
          "sha256": "b551037cd5dade368034c1744d0d1bb42902cecdc0f83389213acc7fd83ffe97",
          "sha1": "daf61a4d334ab69ad2d272ed09aa888362526683",
          "md5": "1d150b0d5741218895af83b42f259988"
        }
      ]
    }
  ]
}
