{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439613,
          "sha512": "5796af8028f0f85228e8e5d3faca261d9e22e5f839ae54ad063762b944a6dbaa4ae29eb132122a9e28824cd4a67ac3b02e102ad537602db902a9a75d4019c4ba",
          "sha256": "030c4fdd34289b8f32c1bc47c539a6842eefe5c40f961b93cb01db8ff64635ea",
          "sha1": "fc914897a9fd3bb57d8cbd5aad54a12d64d3fe8d",
          "md5": "b4d18d36ba807032239a458493c048b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439613,
          "sha512": "5796af8028f0f85228e8e5d3faca261d9e22e5f839ae54ad063762b944a6dbaa4ae29eb132122a9e28824cd4a67ac3b02e102ad537602db902a9a75d4019c4ba",
          "sha256": "030c4fdd34289b8f32c1bc47c539a6842eefe5c40f961b93cb01db8ff64635ea",
          "sha1": "fc914897a9fd3bb57d8cbd5aad54a12d64d3fe8d",
          "md5": "b4d18d36ba807032239a458493c048b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-7.2.0-sources.jar",
          "url": "yieldlove-7.2.0-sources.jar",
          "size": 201111,
          "sha512": "4184b0dc04058ea6a14550bfb400e2b05084fbab4c7b62c76cf63ebdead8ed0624697f77cfa45135fee55f7849c0c7f5bcdb692de95ee60817780c4a4679c570",
          "sha256": "5502df2f58c0ebd810204c584efddfa0c800feaf0d534f0914a63b14d283815d",
          "sha1": "61e9283bd1032b04ec2dd08d8248c4d5212b4566",
          "md5": "bab3fcece43a458fccbccd6b4ad55161"
        }
      ]
    }
  ]
}
