{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439639,
          "sha512": "0b64b9e856a21b9016103fede9699d2672337c9d5ac6fbef6e8049b6d308973e3deb6404feda1fc4fdb14f25a682181672feaf2d19cbe426b916125d6c42ddae",
          "sha256": "d4311f2f9f4b260fe84421d3d64ba894c493875efe0379456a9304fea6973185",
          "sha1": "5c55bf702b0e34e8a31bd3d4c4cdb1adb432c59d",
          "md5": "cefb088b0e4c516ab28d8ce150994f1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.2.0.aar",
          "url": "yieldlove-7.2.0.aar",
          "size": 439639,
          "sha512": "0b64b9e856a21b9016103fede9699d2672337c9d5ac6fbef6e8049b6d308973e3deb6404feda1fc4fdb14f25a682181672feaf2d19cbe426b916125d6c42ddae",
          "sha256": "d4311f2f9f4b260fe84421d3d64ba894c493875efe0379456a9304fea6973185",
          "sha1": "5c55bf702b0e34e8a31bd3d4c4cdb1adb432c59d",
          "md5": "cefb088b0e4c516ab28d8ce150994f1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-7.2.0-sources.jar",
          "url": "yieldlove-7.2.0-sources.jar",
          "size": 201188,
          "sha512": "40e4efab0ce419e1a49562d69544764358410cbd8e113ae8924e48bf17eb833623750d9b7f477b7a00827446931d7b349516a169ab9ad6f64ddcde1a635a40c5",
          "sha256": "58b219ddeab989c36583c827386ffa097960aee6a68a8b9cec2a141a9224479f",
          "sha1": "7f4ff9c3c623ff835902fe58c4a5a36a33e36993",
          "md5": "e7590689518a884ad35feafbdec92af3"
        }
      ]
    }
  ]
}
