{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.0.aar",
          "url": "yieldlove-8.2.0.aar",
          "size": 607279,
          "sha512": "0a20fba3e7b9c848381313107f745601b4ca9ee9d53c6ddc85e8ae858ce3a3947aa02636d61f2d013a3ac7ce0ffde032f67da0c48c30f6c40302b55becbd9b30",
          "sha256": "80075f3bb911226dc01523cd6109e7ce08e013a9731e9269d564f4d0c94d749e",
          "sha1": "79f270ef5f6c841acf0eda27f37ac3277470f6ef",
          "md5": "ef55a950e3239a57b7500bfecf55bec0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "strictly": "4.12.0",
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.0.aar",
          "url": "yieldlove-8.2.0.aar",
          "size": 607279,
          "sha512": "0a20fba3e7b9c848381313107f745601b4ca9ee9d53c6ddc85e8ae858ce3a3947aa02636d61f2d013a3ac7ce0ffde032f67da0c48c30f6c40302b55becbd9b30",
          "sha256": "80075f3bb911226dc01523cd6109e7ce08e013a9731e9269d564f4d0c94d749e",
          "sha1": "79f270ef5f6c841acf0eda27f37ac3277470f6ef",
          "md5": "ef55a950e3239a57b7500bfecf55bec0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.2.0-sources.jar",
          "url": "yieldlove-8.2.0-sources.jar",
          "size": 163785,
          "sha512": "0f3b7a28981b3b55756581ad5a6e88e8ad0e632c310affc8ca2765f4685c4f32475d83f96321b32ce69003d35accbb93393fe8a3eec3f4a3d0540042b4dc1dbb",
          "sha256": "c142bbaa2fb8a7fac700ceea1c6f93f83ee7688a049327d0fbe99d00e9911363",
          "sha1": "a3dd40cf467abf02dcfa532d0cfe0eb88b2b941f",
          "md5": "99a043c1b8c085d8c04370ee637eaecc"
        }
      ]
    }
  ]
}
