{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.0.aar",
          "url": "yieldlove-8.2.0.aar",
          "size": 607040,
          "sha512": "fbbb7e2834916aa7f721fb83e7f77463f8825f6f82d1c38bab46d533e83a1785168a4132626b4ae6be50e38c455aae693a19c3d518bfecede6ff40f9e6f9361a",
          "sha256": "ae180f370a1ce859827d243d0262bc7e319df84f5ff3bcb5313a33552b5581ba",
          "sha1": "b54383592879e06bcf0b0c4f99072a49e1788594",
          "md5": "540a3732e9d4776eb059032c1fee3dcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "strictly": "4.12.0",
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.0.aar",
          "url": "yieldlove-8.2.0.aar",
          "size": 607040,
          "sha512": "fbbb7e2834916aa7f721fb83e7f77463f8825f6f82d1c38bab46d533e83a1785168a4132626b4ae6be50e38c455aae693a19c3d518bfecede6ff40f9e6f9361a",
          "sha256": "ae180f370a1ce859827d243d0262bc7e319df84f5ff3bcb5313a33552b5581ba",
          "sha1": "b54383592879e06bcf0b0c4f99072a49e1788594",
          "md5": "540a3732e9d4776eb059032c1fee3dcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.2.0-sources.jar",
          "url": "yieldlove-8.2.0-sources.jar",
          "size": 163713,
          "sha512": "7188bf3ece726c30b6fd4c538bc71eb76f189b709b5735b9726e2811d6b29ce9277bf8e3de4e3728de1724f3a718c5460597a051dd0223028fe7eb7fa296b5c4",
          "sha256": "ffe04410b9542d9f5ccfe9a87ad4606f0470ac8bc25cc7fcb83f00d66f8d3e24",
          "sha1": "dd87d2a00e2fdac504253698801e304e336cdaad",
          "md5": "6cff0f08fc06bc3a79a1965c1071a9ec"
        }
      ]
    }
  ]
}
