{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "compose",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.0.aar",
          "url": "compose-8.3.0.aar",
          "size": 44039,
          "sha512": "ed9af30df18f94b2cacfed1fd0cdca7c699b84e74e84c2de57887505b7094ea413a0232c011adf6fcf30897f2ac61d43f3749221081333f18ca60bb87b0e64c9",
          "sha256": "279627e6c75dafcddc2054457083fc4add967fc1f017077fba831b12e4b830c3",
          "sha1": "563fee6c95fd3bf5b3ed62e113c6cd6bd8b21daa",
          "md5": "af0c210c019205cc50b08496922626bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.0.aar",
          "url": "compose-8.3.0.aar",
          "size": 44039,
          "sha512": "ed9af30df18f94b2cacfed1fd0cdca7c699b84e74e84c2de57887505b7094ea413a0232c011adf6fcf30897f2ac61d43f3749221081333f18ca60bb87b0e64c9",
          "sha256": "279627e6c75dafcddc2054457083fc4add967fc1f017077fba831b12e4b830c3",
          "sha1": "563fee6c95fd3bf5b3ed62e113c6cd6bd8b21daa",
          "md5": "af0c210c019205cc50b08496922626bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-8.3.0-sources.jar",
          "url": "compose-8.3.0-sources.jar",
          "size": 9153,
          "sha512": "719094e3c7baaec67efdcfde541d7c31991036ce59f7fa01e51c59429f854aa07f634735ae866374a58758ae265d1cae91b443c313f36c3e19b0336f742e415e",
          "sha256": "349e28aa3bdd5f2354da2bf41d5c4f7884cb9826ff111c9ff8ebcf6324ac313a",
          "sha1": "976347d98c030fdafb2cd64cf35629b02dce76fd",
          "md5": "18fc3f4bde6597ca8597d7e4f37b1a1e"
        }
      ]
    }
  ]
}
