{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "compose",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.0.aar",
          "url": "compose-8.3.0.aar",
          "size": 44043,
          "sha512": "bbbc3ca30eb2b1c4dc7996c60a095182fcfda78b297b5ce8f79e2e2991c831c6c2d09b014ed6d44cfd5c81bedbdabdfadf3b86d6d24edcf32b432a1f003ef939",
          "sha256": "4706199bd1dc467b3710b9dfb21a6704868a1fbdf32fe211611294e9f1456789",
          "sha1": "9dede2fea58d8a85b12bd96a165fa344be9730e7",
          "md5": "dd827068a4e48668b7696f2538866181"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.0.aar",
          "url": "compose-8.3.0.aar",
          "size": 44043,
          "sha512": "bbbc3ca30eb2b1c4dc7996c60a095182fcfda78b297b5ce8f79e2e2991c831c6c2d09b014ed6d44cfd5c81bedbdabdfadf3b86d6d24edcf32b432a1f003ef939",
          "sha256": "4706199bd1dc467b3710b9dfb21a6704868a1fbdf32fe211611294e9f1456789",
          "sha1": "9dede2fea58d8a85b12bd96a165fa344be9730e7",
          "md5": "dd827068a4e48668b7696f2538866181"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-8.3.0-sources.jar",
          "url": "compose-8.3.0-sources.jar",
          "size": 9153,
          "sha512": "258e219924a4c989a0fb47d2d7be2f7ffee6af77aa2280120eafbc51a807207a10facc8d38bd038c032ac5621ff31762fa55a181961b660fd3f8b5d3b17ab5ab",
          "sha256": "99262c3cdc7fb1f7c45a097168a758ca3274829fd53df7f5e1ed5fd34edee3be",
          "sha1": "d7d4e5b447eca1ca00c26b42ecb8fe159cb18a41",
          "md5": "c26ed03459c8018e4c32aec9008a04b0"
        }
      ]
    }
  ]
}
