{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 43965,
          "sha512": "c9d1323be5c5da4e02e8f23b4b1989b0f8a9e1d619c533ffa99cc5e58c68827088147d0f33da5f37a72a19c8367816cc511b014ac3d3b69e0767db6e863403fc",
          "sha256": "dd3c02ba8015718583b5d6f79f27eafe400615ef604934d3f8edd3216e6ca39b",
          "sha1": "563791ff063904203c430bc05dae35f1bf596e3f",
          "md5": "ecf392624d110d56a74b934a058f56f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 43965,
          "sha512": "c9d1323be5c5da4e02e8f23b4b1989b0f8a9e1d619c533ffa99cc5e58c68827088147d0f33da5f37a72a19c8367816cc511b014ac3d3b69e0767db6e863403fc",
          "sha256": "dd3c02ba8015718583b5d6f79f27eafe400615ef604934d3f8edd3216e6ca39b",
          "sha1": "563791ff063904203c430bc05dae35f1bf596e3f",
          "md5": "ecf392624d110d56a74b934a058f56f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-1.0.0-sources.jar",
          "url": "compose-1.0.0-sources.jar",
          "size": 9104,
          "sha512": "72d9092c8b593c4208b6c9ccc92f5b403930f6eba750791ccae06945659078b0ccea52d169aceaf6ce83884effb348a8c67b1dceac95f496b076eb9feba7c15d",
          "sha256": "15ccca2a68c7ffc9b8348a1a0e93c7ef194c4870a67463577486342b2a77178b",
          "sha1": "57c7ce6dd1bfafafc6736fc4546bec5259d30510",
          "md5": "38a799fb134d11342285a0a678c7d028"
        }
      ]
    }
  ]
}
