{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 47940,
          "sha512": "510423f586b0d079d39c8544eaafc86a89a3f98264039ee7c3e2fa2635c62405cec9131e4e785678ae9c790930823989a3659b469fef63029b31627846718304",
          "sha256": "3d2664bd08f236ea8dfc1211d5e18b5ff57c5fa5683f9b3d75a465953f4bacc4",
          "sha1": "d8cb58c99d3c914287c57165bcb48f1792d28041",
          "md5": "af680c9408797542cc8297d62ac9ff05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0.aar",
          "url": "compose-1.0.0.aar",
          "size": 47940,
          "sha512": "510423f586b0d079d39c8544eaafc86a89a3f98264039ee7c3e2fa2635c62405cec9131e4e785678ae9c790930823989a3659b469fef63029b31627846718304",
          "sha256": "3d2664bd08f236ea8dfc1211d5e18b5ff57c5fa5683f9b3d75a465953f4bacc4",
          "sha1": "d8cb58c99d3c914287c57165bcb48f1792d28041",
          "md5": "af680c9408797542cc8297d62ac9ff05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-1.0.0-sources.jar",
          "url": "compose-1.0.0-sources.jar",
          "size": 10574,
          "sha512": "1003c407e6fdb4b377ac06040f8d0ba4aa10f55364847d1742b7b07594a82f43480b2b9d042dc7ee06ffb11e6e99a8324aa75e2ee7f6e588d5da6e7df8c24fd2",
          "sha256": "f69b436ecc847046e8173565ff67f2ed93908ed1e958fbf166781bd944dae166",
          "sha1": "f7ebca98e2b44b7ac6b031bd1d7560c597b06503",
          "md5": "ecdd9a85b379cfe8a30a3c893bf8ff37"
        }
      ]
    }
  ]
}
