{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.2.aar",
          "url": "confiant-8.0.2.aar",
          "size": 5514,
          "sha512": "558cb75d9e7db21a1cfd06e95efe546c6875d1f80c3a90446cc4dd7680ebcd78052aef022104a1d17959a0783492e1aad3752720d7d425d38434e678a1251f00",
          "sha256": "2c92161b395f426a705352b98602a2bbf40bc3b059d4a1d124c66340287dd6a1",
          "sha1": "598ee239556f468f1de00982a327acba8bf9c5af",
          "md5": "bf33c32a55476d5262fe6532df0c7751"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.2.aar",
          "url": "confiant-8.0.2.aar",
          "size": 5514,
          "sha512": "558cb75d9e7db21a1cfd06e95efe546c6875d1f80c3a90446cc4dd7680ebcd78052aef022104a1d17959a0783492e1aad3752720d7d425d38434e678a1251f00",
          "sha256": "2c92161b395f426a705352b98602a2bbf40bc3b059d4a1d124c66340287dd6a1",
          "sha1": "598ee239556f468f1de00982a327acba8bf9c5af",
          "md5": "bf33c32a55476d5262fe6532df0c7751"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.0.2-sources.jar",
          "url": "confiant-8.0.2-sources.jar",
          "size": 3388,
          "sha512": "5c05bdf918d77959fe24e85cea53c92065495fabd0443e2b71af4904d9cb4753ba3ffef76aa74c1be2c843429d6521bc87a6efbf16bdfa4debf657f70a217fbb",
          "sha256": "db9cead626fde5a2a439782eea2701168971a1cba14dbc57cb5145036b5a4353",
          "sha1": "ed8ca251eb411dfb43bf746091075515ffaf4250",
          "md5": "abb077c1a52082cc3168a828bc95a537"
        }
      ]
    }
  ]
}
