{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.1.aar",
          "url": "confiant-8.3.1.aar",
          "size": 6589,
          "sha512": "dab3d7c0697b9c5ff528c98fcab39370929d3ad913c5495390c9f9e1bec9a8f10734a451cf5fc0a0c7ffc787c4a843a4cf1cd5a471094ef72544d90680aa2dab",
          "sha256": "002a483374f5b220458a22ec443927d15c6fe8de1f6ea56435776f9646e0e2b8",
          "sha1": "411f708fd147db63b926a31a1dfff27a5b87824d",
          "md5": "047d2c180cbb2e3b9cf3b100ed62863a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.1.aar",
          "url": "confiant-8.3.1.aar",
          "size": 6589,
          "sha512": "dab3d7c0697b9c5ff528c98fcab39370929d3ad913c5495390c9f9e1bec9a8f10734a451cf5fc0a0c7ffc787c4a843a4cf1cd5a471094ef72544d90680aa2dab",
          "sha256": "002a483374f5b220458a22ec443927d15c6fe8de1f6ea56435776f9646e0e2b8",
          "sha1": "411f708fd147db63b926a31a1dfff27a5b87824d",
          "md5": "047d2c180cbb2e3b9cf3b100ed62863a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.3.1-sources.jar",
          "url": "confiant-8.3.1-sources.jar",
          "size": 3246,
          "sha512": "612dbd7196514d3620d4717546e25fe4392497c3151d887142cb9444f75a3875bb644594786fb610100af80ca313f1b1d3fa513791a97b15575eacbae2721cbb",
          "sha256": "0114400be1b4e23a4f3b126eb329690de0d7c349cdf7366bd25e48b21a43d0e7",
          "sha1": "b4158489de8f72fdfe52bdd169ed875f8c07ecf2",
          "md5": "63eedef37cd72f22dd134b43f5d98a39"
        }
      ]
    }
  ]
}
