{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.2.aar",
          "url": "confiant-8.2.2.aar",
          "size": 6593,
          "sha512": "b241add24ea4c54805019860168a6589e96d35141bffff5a2f365dc38aab358107209aaadc129af5678c1179c99bd0b1441b58724beb65800adcb317574e37c6",
          "sha256": "cf34652abdd0e4e7c8b89ee26752a2e0ed8c0d0cc80f8de184ad9a88fca2e724",
          "sha1": "0f9600b1f2dde350a48d8f5c4a6d187e01cd8c3d",
          "md5": "32ad0c6dbd5488e62d2007bac567c2c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.2.aar",
          "url": "confiant-8.2.2.aar",
          "size": 6593,
          "sha512": "b241add24ea4c54805019860168a6589e96d35141bffff5a2f365dc38aab358107209aaadc129af5678c1179c99bd0b1441b58724beb65800adcb317574e37c6",
          "sha256": "cf34652abdd0e4e7c8b89ee26752a2e0ed8c0d0cc80f8de184ad9a88fca2e724",
          "sha1": "0f9600b1f2dde350a48d8f5c4a6d187e01cd8c3d",
          "md5": "32ad0c6dbd5488e62d2007bac567c2c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.2.2-sources.jar",
          "url": "confiant-8.2.2-sources.jar",
          "size": 3245,
          "sha512": "c52e655b09421efcc981fb944db2caa169b0b4840a67aa2f994f37d72db2152ddaa0d9e4d1e73e5a757513fe99c8f6d5d88f0a38d9f864020d3ad5209f782d24",
          "sha256": "1c938307d01330406b59566cc964cd2c14ddf7b21be10bac7072d9bc6820991a",
          "sha1": "b26a65dd13739dc879e6aee5d69045b8e04de0ad",
          "md5": "7f88ac5cc1432cf53665b2ecb7bdfe99"
        }
      ]
    }
  ]
}
