{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15052,
          "sha512": "400acf668dff494dcb34692b50bfbcd32b723ac1c6ba4b8736e01eb5c7cc173a63af6dc49b00e475bc84541f545a28ac85d235e20ac91514556a6cb1642310da",
          "sha256": "e6a9a334816a1f85fdefc0970f00010b8f69a8ce41ba99b77a3dac5a5282a4e0",
          "sha1": "1b94ee017ed26f3c822b666a15b48183e0ada7b0",
          "md5": "3069bdfb39ed62df2e7b59773a3addb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.13.6"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15052,
          "sha512": "400acf668dff494dcb34692b50bfbcd32b723ac1c6ba4b8736e01eb5c7cc173a63af6dc49b00e475bc84541f545a28ac85d235e20ac91514556a6cb1642310da",
          "sha256": "e6a9a334816a1f85fdefc0970f00010b8f69a8ce41ba99b77a3dac5a5282a4e0",
          "sha1": "1b94ee017ed26f3c822b666a15b48183e0ada7b0",
          "md5": "3069bdfb39ed62df2e7b59773a3addb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-7.2.0-sources.jar",
          "url": "gravite-7.2.0-sources.jar",
          "size": 10334,
          "sha512": "874fdaf341c0a3a3aadfd233a6276579564be8b852d3fe104514ece746f251119056eb8241b7655edb21c92c5893d2b80e764f25369045a6de8e24fb8725af02",
          "sha256": "88f525f3a086ceb53b8aaeeb143298a88e1c937926e01004be77ddc1ea050dde",
          "sha1": "198e131790071cc2908023d60f381c93dc7a1582",
          "md5": "d92d576a95d496563bcbe9f060c6ddd9"
        }
      ]
    }
  ]
}
