{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15064,
          "sha512": "dd9ae4165a0cae2d36391fa0fec5df85999740eda0318eefc3bac5e319cde71f380ef5e95f10a2c6a1744687c485907ece2a0d28a5674310e44c05577d4f843b",
          "sha256": "2b701a2e8a65c21cd9ad57ebf02c0512f6de0cbb2ccf5b38121634cce7c54aaa",
          "sha1": "7e458946e20107a60e44cf69a5a14144f332be0a",
          "md5": "9315dbd2c8f880b1bbaec4dee292993a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.13.6"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15064,
          "sha512": "dd9ae4165a0cae2d36391fa0fec5df85999740eda0318eefc3bac5e319cde71f380ef5e95f10a2c6a1744687c485907ece2a0d28a5674310e44c05577d4f843b",
          "sha256": "2b701a2e8a65c21cd9ad57ebf02c0512f6de0cbb2ccf5b38121634cce7c54aaa",
          "sha1": "7e458946e20107a60e44cf69a5a14144f332be0a",
          "md5": "9315dbd2c8f880b1bbaec4dee292993a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-7.2.0-sources.jar",
          "url": "gravite-7.2.0-sources.jar",
          "size": 10336,
          "sha512": "bda6ca72268e64aadb36f994d63d098c824269b7ebf15a98b6df76124bd61ff80130e6ba7334f5098ae335d063a55f77861a2495f5d8f0ac93ed345907fe7818",
          "sha256": "9d0f4b958a3f2226ea5bf2f5f2778d892062c71d846ed93f670d3dbfc858fe9f",
          "sha1": "99a5080443a2f62c942327ab57d2c5b76673abff",
          "md5": "3d515ed28246d3ee95efa2f0eebe936e"
        }
      ]
    }
  ]
}
