{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15066,
          "sha512": "051e59cf7fadadcc3b2f9200c1425ac2a299edf804821e5732dc62b0dc2bb9f354a2aab83ded375af469a326e39d38864dc0e96c0d54b0dbe66df66300a2d94c",
          "sha256": "e3cd01d37a3b405bd164cf12226961d9069699cb4ca0ee70052bd8324f549ecf",
          "sha1": "5d07094091e4a0a44ae9f1cc13e4ea52c0754232",
          "md5": "629d1308a21538acefad7975831706c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.13.6"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-7.2.0.aar",
          "url": "gravite-7.2.0.aar",
          "size": 15066,
          "sha512": "051e59cf7fadadcc3b2f9200c1425ac2a299edf804821e5732dc62b0dc2bb9f354a2aab83ded375af469a326e39d38864dc0e96c0d54b0dbe66df66300a2d94c",
          "sha256": "e3cd01d37a3b405bd164cf12226961d9069699cb4ca0ee70052bd8324f549ecf",
          "sha1": "5d07094091e4a0a44ae9f1cc13e4ea52c0754232",
          "md5": "629d1308a21538acefad7975831706c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-7.2.0-sources.jar",
          "url": "gravite-7.2.0-sources.jar",
          "size": 10336,
          "sha512": "4a0ae81bc5a94eed81ca1a748ec14757f5811aef947af0a96f0767ab370a169cba79bdbb6c1941348100b5689670cac1e7a66e3eb47c8d8c9b0af24099b8c9d0",
          "sha256": "6d2d365b7152f395233217ec26ac9d2b13d8df2d4720353a1af07fd868f4e4e6",
          "sha1": "8648a1595d0ea97c95b020ec76927c4789d29416",
          "md5": "f73f87e78a8615dab562e2a4792e8e39"
        }
      ]
    }
  ]
}
