{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.2.0.aar",
          "url": "gravite-8.2.0.aar",
          "size": 20467,
          "sha512": "b318778e6cb557d084a0268deb3f9524cc8b9df42dc299a80b9a063aa19b59f663c8ee8e27fad8f6d4bf93a4041c0cfc8c20c661b8cd635f135752e9afaa03e8",
          "sha256": "77c3a9871dcf71a93326134ed06f930fe254bd117a7584b037ec455d2bb2903f",
          "sha1": "90abfe278836ba3c08ead6831d6f96b107239991",
          "md5": "6c98736b245baea099dc51d5e0b43a68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.14.3"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.2.0.aar",
          "url": "gravite-8.2.0.aar",
          "size": 20467,
          "sha512": "b318778e6cb557d084a0268deb3f9524cc8b9df42dc299a80b9a063aa19b59f663c8ee8e27fad8f6d4bf93a4041c0cfc8c20c661b8cd635f135752e9afaa03e8",
          "sha256": "77c3a9871dcf71a93326134ed06f930fe254bd117a7584b037ec455d2bb2903f",
          "sha1": "90abfe278836ba3c08ead6831d6f96b107239991",
          "md5": "6c98736b245baea099dc51d5e0b43a68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-8.2.0-sources.jar",
          "url": "gravite-8.2.0-sources.jar",
          "size": 10433,
          "sha512": "8e86034665072701f3c72055fc75dffcc8b48892181389fe3046dbafa17f7da087765911bbf1d82962bddefbd6fc97af608aec3af7064e05855f512de341bced",
          "sha256": "4e484b74a9d34718e8effc7a7db6d252babc8589c25cee090064d73ae8bf3288",
          "sha1": "7f713539f0a20df249edbf0a3582fd4dfcd485fb",
          "md5": "36b5263e50354ba421a1b18e142d1e4c"
        }
      ]
    }
  ]
}
