{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28191,
          "sha512": "caf1dd17b71cb9a2f5c29dbfb6605fa719d9b9d66fc1933d1d51de24b2f9953d39f21ce0cea2c2df5822e8812150ac637cab18e03fea9604ced7afde96e604a4",
          "sha256": "208f5dc175d47eb47d9bf65f98eae4a74032a3e41f055bbf173bd4229440bcce",
          "sha1": "6167dc04f725469a4a552ebb8b99b2e37306528e",
          "md5": "b3204c8ced9cee90fc38d42d638ad552"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28191,
          "sha512": "caf1dd17b71cb9a2f5c29dbfb6605fa719d9b9d66fc1933d1d51de24b2f9953d39f21ce0cea2c2df5822e8812150ac637cab18e03fea9604ced7afde96e604a4",
          "sha256": "208f5dc175d47eb47d9bf65f98eae4a74032a3e41f055bbf173bd4229440bcce",
          "sha1": "6167dc04f725469a4a552ebb8b99b2e37306528e",
          "md5": "b3204c8ced9cee90fc38d42d638ad552"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.3.0-sources.jar",
          "url": "cmp-8.3.0-sources.jar",
          "size": 5705,
          "sha512": "b46f7dab98255ec6567d46dbf8830892f038eae2f3fe128006de381bd6bd9e66cfad207a24fa9ac4ba58cba60d53df62f86d98002b3c0bf853b75ea36002f695",
          "sha256": "b8b00d67931bb4583f71c8b5b40df82f3968526607837c322d16fe3fe2b34240",
          "sha1": "7dfc1e3a98dde93c81cc0e216612d45eade9497b",
          "md5": "663ea5a5cf792e08315b8dfed295da38"
        }
      ]
    }
  ]
}
