{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28190,
          "sha512": "41fa490d434229d2676632d66071aaba64f2790cee01d59674848ae637144454b78fb772f130a4f35e97ecace9baabd251b4c18e80de2ce5fd4ad3da2468f403",
          "sha256": "9b69641bcd28cf020ebdf3ab1a55789dc1bf5da666bd71fc7871f16e70d267f6",
          "sha1": "ac04bfbf3595e894dee8ca4b83b32e9b64c00342",
          "md5": "b033dab1d83482452173710c13de47a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28190,
          "sha512": "41fa490d434229d2676632d66071aaba64f2790cee01d59674848ae637144454b78fb772f130a4f35e97ecace9baabd251b4c18e80de2ce5fd4ad3da2468f403",
          "sha256": "9b69641bcd28cf020ebdf3ab1a55789dc1bf5da666bd71fc7871f16e70d267f6",
          "sha1": "ac04bfbf3595e894dee8ca4b83b32e9b64c00342",
          "md5": "b033dab1d83482452173710c13de47a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.3.0-sources.jar",
          "url": "cmp-8.3.0-sources.jar",
          "size": 5705,
          "sha512": "32fbe6383e7720af3bfbc0b4ccd2a97ab4938293e7031aab03513ee0e90ba7d86f8e882b61c3ad83e93f355c40660f4b44a2734c6257c89a77657a2863428ff9",
          "sha256": "60e20b0229324ff37c6c4628a14f54cc8266241bb6571cb64c70819a814b8dea",
          "sha1": "6569a01bddb39a2a227c03d57b5ecf589e7c52a7",
          "md5": "c6ec2984c290459a9bdc1c71192db43e"
        }
      ]
    }
  ]
}
