{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28185,
          "sha512": "2855f41e4f7897ee40fe4c15236db6ade31d3a855c57d17bbe524ce46f14347ee84c08f92ff5da1117895a35219af5005ff4545d76dc3e369f911ac4649c92db",
          "sha256": "ad28067bcda77a7764d265647a407fd3bf5791ed9c7096bfb7fc6d71e402f7be",
          "sha1": "84023d76040e9b173989cbe84b0f14ea0994f848",
          "md5": "d7a03bd7a5b367c8e987cdc809f0a803"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.0.aar",
          "url": "cmp-8.3.0.aar",
          "size": 28185,
          "sha512": "2855f41e4f7897ee40fe4c15236db6ade31d3a855c57d17bbe524ce46f14347ee84c08f92ff5da1117895a35219af5005ff4545d76dc3e369f911ac4649c92db",
          "sha256": "ad28067bcda77a7764d265647a407fd3bf5791ed9c7096bfb7fc6d71e402f7be",
          "sha1": "84023d76040e9b173989cbe84b0f14ea0994f848",
          "md5": "d7a03bd7a5b367c8e987cdc809f0a803"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.3.0-sources.jar",
          "url": "cmp-8.3.0-sources.jar",
          "size": 5705,
          "sha512": "5c622e0660e020c5ff7e89d00da2708ce8baad98cb3cc84523320ae636162acd99cb6086a33b7dc877fb7d22d9d645634f236477301c9bcc4ac16b675212df84",
          "sha256": "4d01fb4839d200d886db918878b813d9deac4b20bab6784c0b086b2b6166258f",
          "sha1": "5b337f579a4c858618e2834264036142f3bb1285",
          "md5": "47e06bdd6349563322c19e629fb02bf0"
        }
      ]
    }
  ]
}
