{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "core",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.0.aar",
          "url": "core-0.0.0.aar",
          "size": 660086,
          "sha512": "f043f341aa5fb5ee81405d1ae6a330cfe704defb39e19e486860c4020dd670e68af9af956a3ed2e7dcd9d104565be7ca98f87867300edb7438cd18752f7eab27",
          "sha256": "c63f110c30ffd0f6d46ec10e24550df40a2f247ac004a113b2107f4e0af18689",
          "sha1": "402013ac35bbd640802af907eadab7f03a55d5e1",
          "md5": "fda494c0722427ca1071d20c521a217d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.0.aar",
          "url": "core-0.0.0.aar",
          "size": 660086,
          "sha512": "f043f341aa5fb5ee81405d1ae6a330cfe704defb39e19e486860c4020dd670e68af9af956a3ed2e7dcd9d104565be7ca98f87867300edb7438cd18752f7eab27",
          "sha256": "c63f110c30ffd0f6d46ec10e24550df40a2f247ac004a113b2107f4e0af18689",
          "sha1": "402013ac35bbd640802af907eadab7f03a55d5e1",
          "md5": "fda494c0722427ca1071d20c521a217d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.0.0-sources.jar",
          "url": "core-0.0.0-sources.jar",
          "size": 161961,
          "sha512": "ff266dc5657cbee59b47ed2deb321bdb011da6ff79381b4e5eb0368b63d7612b1dbe2d6a12b6bb0b462776afbc29476805c97958957a1dd72f1494475d69437a",
          "sha256": "cfe51a1f3dc9f3cfda2472749931f3ca293732ae580df106506df8cb1f1c555e",
          "sha1": "bb855e11229864e249f315825c69800f9cea086a",
          "md5": "493b5341fae33025f9e1cfbf101f5064"
        }
      ]
    }
  ]
}
