{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.1.aar",
          "url": "yieldlove-8.3.1.aar",
          "size": 659169,
          "sha512": "aefabe7d7fd6f95bdb22ac3623f8e54b4cae452d8232e09cf91eb40f5e9edef3e889cb416aaf8854a8814a08b30ca596352b8e99fff7c7de9cc9f961161df1ab",
          "sha256": "483e53687b66abd28670f495a81170c6382acf5dab61c259618de0563475e464",
          "sha1": "bde6fe5f607a871827650c0de18abe8b9072af25",
          "md5": "4b7d245e630acfea436b7c9997b47a31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.1.aar",
          "url": "yieldlove-8.3.1.aar",
          "size": 659169,
          "sha512": "aefabe7d7fd6f95bdb22ac3623f8e54b4cae452d8232e09cf91eb40f5e9edef3e889cb416aaf8854a8814a08b30ca596352b8e99fff7c7de9cc9f961161df1ab",
          "sha256": "483e53687b66abd28670f495a81170c6382acf5dab61c259618de0563475e464",
          "sha1": "bde6fe5f607a871827650c0de18abe8b9072af25",
          "md5": "4b7d245e630acfea436b7c9997b47a31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.3.1-sources.jar",
          "url": "yieldlove-8.3.1-sources.jar",
          "size": 162926,
          "sha512": "fa9dce29829fcfd1dc2bc943bb37fbc2cbde9b8f4a4805de16902975fe7f81894406315825b6bfe7e7fe62091b528b55f56b71228c26a1276bb62ecfec9cab8f",
          "sha256": "3f3a4885b48b3c5c5139f8aef80eeb3335b34b4ccc80d3a2b2cc7965b7f86c18",
          "sha1": "c57f3c41416827ff6166454d4015144758b94dd6",
          "md5": "a27a3d4e6ba6145cbdcd41a71020c4df"
        }
      ]
    }
  ]
}
