{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.1.aar",
          "url": "yieldlove-8.3.1.aar",
          "size": 659169,
          "sha512": "9e57a326655493df7ae80fab395f24bc23842d94678d5406559d23951487798f646d32f30530f9e9afd898d6747f0d2edae2bf9533f6b645e2f51a572583668a",
          "sha256": "3ac6af3143ece549077329c9b0d6e76fcd181519131b8f7677a4cc4736b23c8d",
          "sha1": "9e761f27ebf4ab5e7746a558bf32106b5d93b9fa",
          "md5": "a6ae56171f7fac1c1baa0ced9cd50cdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.1.aar",
          "url": "yieldlove-8.3.1.aar",
          "size": 659169,
          "sha512": "9e57a326655493df7ae80fab395f24bc23842d94678d5406559d23951487798f646d32f30530f9e9afd898d6747f0d2edae2bf9533f6b645e2f51a572583668a",
          "sha256": "3ac6af3143ece549077329c9b0d6e76fcd181519131b8f7677a4cc4736b23c8d",
          "sha1": "9e761f27ebf4ab5e7746a558bf32106b5d93b9fa",
          "md5": "a6ae56171f7fac1c1baa0ced9cd50cdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.3.1-sources.jar",
          "url": "yieldlove-8.3.1-sources.jar",
          "size": 162926,
          "sha512": "12b02e49317c3ccd927e0faf7d420f8be9c9232fa4ab78248f96774d99d81144f10410352b90934dd648949872ca5156e5636fce8b62ec731b31ae2275dd7bc4",
          "sha256": "4c9138705abdb55faae2baff914d65a20376804e319122da018d4156ba7c7998",
          "sha1": "1692eb00a086d4c326a4c66f55d90b8e9c2c8bcc",
          "md5": "59761d0950d753128e1efb3b4152bba7"
        }
      ]
    }
  ]
}
