{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6585,
          "sha512": "3a99f9f55696ef4356b50742e42a220ae289b5179d7fcddf73fc401126fc46d7d9fa4e428d900723dfbd4a255708c17fb359f1fed2fb356a4454bdefb0169059",
          "sha256": "56a9049c6a9c761d1b9768a673c4d81b19065a8a041a91334ee8e64e2f0a52d0",
          "sha1": "c80bbb87e2c192991554032f1ed9ef9cbb620fbf",
          "md5": "1eb007ca2385d8dbd0c6f505146a7553"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6585,
          "sha512": "3a99f9f55696ef4356b50742e42a220ae289b5179d7fcddf73fc401126fc46d7d9fa4e428d900723dfbd4a255708c17fb359f1fed2fb356a4454bdefb0169059",
          "sha256": "56a9049c6a9c761d1b9768a673c4d81b19065a8a041a91334ee8e64e2f0a52d0",
          "sha1": "c80bbb87e2c192991554032f1ed9ef9cbb620fbf",
          "md5": "1eb007ca2385d8dbd0c6f505146a7553"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.3.0-sources.jar",
          "url": "confiant-8.3.0-sources.jar",
          "size": 3244,
          "sha512": "00f6c5ed96b9a79611a510989da58d2f25d698050b6306258d9a659f7ed2b29629ce6cc2996fec797f459231673d831eba77ece7d448463a32eb657eb08ab3e9",
          "sha256": "73d7e865916a530f5a20cee6fdbdf329431b7cbce3ce69b2813dcf5a0c944a50",
          "sha1": "76ea45a3e242579675add59c18c6c1b40993d8a9",
          "md5": "0527af01e8d289b525226630e3d10ad0"
        }
      ]
    }
  ]
}
