{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6586,
          "sha512": "548abb6aa994c8866083ca27c27246e52ca99a22c0341ba9eefa6f68084c76cb6ba21f75e40c44bcbb3ab928cb61d66480be0c1d20e8faeace729f15c47cd0be",
          "sha256": "522369c7b54d509caf4f19fcf29a04fce5ad8971d321bf166b726ebf84d299e2",
          "sha1": "baeb093ac86d191f4728fa64df6cc6e77e818689",
          "md5": "d9b41c0ae5cdc929afd32e6d5c6f7cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6586,
          "sha512": "548abb6aa994c8866083ca27c27246e52ca99a22c0341ba9eefa6f68084c76cb6ba21f75e40c44bcbb3ab928cb61d66480be0c1d20e8faeace729f15c47cd0be",
          "sha256": "522369c7b54d509caf4f19fcf29a04fce5ad8971d321bf166b726ebf84d299e2",
          "sha1": "baeb093ac86d191f4728fa64df6cc6e77e818689",
          "md5": "d9b41c0ae5cdc929afd32e6d5c6f7cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.3.0-sources.jar",
          "url": "confiant-8.3.0-sources.jar",
          "size": 3245,
          "sha512": "08bf1e98d35bdb87b8a90e1805d6d015d2875b13a8803ff62d3c0df35aafbe6f329cfceebbd81ed733871c69282b98f9e6fd4c0f6945f6763b52636ad00ff0af",
          "sha256": "d5968700bf9333b5efab6419e1595f47890d5cbebce9a99aee2ed30a1b7358eb",
          "sha1": "625d6424a603a9f78f50238af22d0d171b839713",
          "md5": "4c8203953f73a8b7aa22a9a5538d3037"
        }
      ]
    }
  ]
}
