{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6586,
          "sha512": "25b8ee755283d4b94612f9421052c8890078783dbde76c126c6475799b82819b6f95b07c860bf99806a1073b14f8de61a82feb29663c5faa32bef068376a63e3",
          "sha256": "d763f353505e40f13285b8ebac1b19b08275b48fb8f169d82a226253150be1fd",
          "sha1": "7b5750f0aa8491b4f53f2b65f9ad458136863709",
          "md5": "c131f0f5b73bd6d50dcf395b25350b2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.3.0.aar",
          "url": "confiant-8.3.0.aar",
          "size": 6586,
          "sha512": "25b8ee755283d4b94612f9421052c8890078783dbde76c126c6475799b82819b6f95b07c860bf99806a1073b14f8de61a82feb29663c5faa32bef068376a63e3",
          "sha256": "d763f353505e40f13285b8ebac1b19b08275b48fb8f169d82a226253150be1fd",
          "sha1": "7b5750f0aa8491b4f53f2b65f9ad458136863709",
          "md5": "c131f0f5b73bd6d50dcf395b25350b2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.3.0-sources.jar",
          "url": "confiant-8.3.0-sources.jar",
          "size": 3245,
          "sha512": "753205a07003c7a3d4981a26ec99511fc69b3002ed47b08906ae55d0083f4c7bdc787e7fc3d6aec88449a18b05c27b4d8ba8d7b741915937d1c44b9a5f998eaf",
          "sha256": "6711bdedf7aa0c6b6794eaed8dc701c702beda6658f26bc75ba7b090b7b42831",
          "sha1": "b64cd4f4c467cefaaf070581101bfd9baacbeeed",
          "md5": "ab9002f7753edbf721560032a33a81a4"
        }
      ]
    }
  ]
}
