{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.0.aar",
          "url": "cmp-8.2.0.aar",
          "size": 25644,
          "sha512": "a251debe352100e323cb2a3a3ddb73863e3a2c1d6198fbddd520ecd9be79c559dbdadd314478f92efd679068c8c20328bae89286662549d0c5f0257ef39920c0",
          "sha256": "6db60ecad99d1b4e1efc37174be8d14fcd32525ea57f3a382832c2bf024c371c",
          "sha1": "eaee1c9b7d401af43b55fe9738acabc1b6cd316d",
          "md5": "8a13bc94faed676888c18dfe4bfdd0af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.0.aar",
          "url": "cmp-8.2.0.aar",
          "size": 25644,
          "sha512": "a251debe352100e323cb2a3a3ddb73863e3a2c1d6198fbddd520ecd9be79c559dbdadd314478f92efd679068c8c20328bae89286662549d0c5f0257ef39920c0",
          "sha256": "6db60ecad99d1b4e1efc37174be8d14fcd32525ea57f3a382832c2bf024c371c",
          "sha1": "eaee1c9b7d401af43b55fe9738acabc1b6cd316d",
          "md5": "8a13bc94faed676888c18dfe4bfdd0af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.2.0-sources.jar",
          "url": "cmp-8.2.0-sources.jar",
          "size": 5713,
          "sha512": "53691d5e82a7e1851c14a08fa2f3e38969f094d05c91fef40a8eb408fa6617aa092ecf228161b957502241f9feab7de1d2d6a34254912965bcb24859136ede68",
          "sha256": "b05684f8d1795a1ad778dc261e1847cb7dd564e1873e2fa28a2b93b2aaba6ccb",
          "sha1": "7c8de2fe7176dec71f94902ea2b6ccad13278fdf",
          "md5": "ca58af6a298e2dfc9b2719d316502615"
        }
      ]
    }
  ]
}
