{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.0.aar",
          "url": "cmp-8.2.0.aar",
          "size": 25597,
          "sha512": "3355a089efae8345562759d500ade779bf924959cad8f04d0e76919229a6d27f41da6a5155a55e55f69b3f6c9a8dfb788aa12690170c255a1c717f02cc13623c",
          "sha256": "8fecfe3c1517026ec8ccdc6417b52b1e301990b6c9fc04ce8e16498ca7241c59",
          "sha1": "a58606d2edb58369eae78b036c23b1e16ec39243",
          "md5": "a69ce98c83818b73b607021e27f9237c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.0.aar",
          "url": "cmp-8.2.0.aar",
          "size": 25597,
          "sha512": "3355a089efae8345562759d500ade779bf924959cad8f04d0e76919229a6d27f41da6a5155a55e55f69b3f6c9a8dfb788aa12690170c255a1c717f02cc13623c",
          "sha256": "8fecfe3c1517026ec8ccdc6417b52b1e301990b6c9fc04ce8e16498ca7241c59",
          "sha1": "a58606d2edb58369eae78b036c23b1e16ec39243",
          "md5": "a69ce98c83818b73b607021e27f9237c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.2.0-sources.jar",
          "url": "cmp-8.2.0-sources.jar",
          "size": 5713,
          "sha512": "53691d5e82a7e1851c14a08fa2f3e38969f094d05c91fef40a8eb408fa6617aa092ecf228161b957502241f9feab7de1d2d6a34254912965bcb24859136ede68",
          "sha256": "b05684f8d1795a1ad778dc261e1847cb7dd564e1873e2fa28a2b93b2aaba6ccb",
          "sha1": "7c8de2fe7176dec71f94902ea2b6ccad13278fdf",
          "md5": "ca58af6a298e2dfc9b2719d316502615"
        }
      ]
    }
  ]
}
