{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "confiant",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0.aar",
          "url": "confiant-1.0.0.aar",
          "size": 6287,
          "sha512": "ca7260b645fab4abbdf9925d2713be2084cbc40d5ffcacd914d445e2e4733883a1a870ec5cffdcae24fc640e6c136b05c9cc448498925f2fca1248f01a1136ba",
          "sha256": "232e5e6cb8432645b6205bfd3206d3e29d6ed9acc46eef2ea6d35bd8cd800f3d",
          "sha1": "792540af5d0f3fbaa38a23ff60be49e3a76c6b79",
          "md5": "3de35ebb9843f7bb450fa77a45682f6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0.aar",
          "url": "confiant-1.0.0.aar",
          "size": 6287,
          "sha512": "ca7260b645fab4abbdf9925d2713be2084cbc40d5ffcacd914d445e2e4733883a1a870ec5cffdcae24fc640e6c136b05c9cc448498925f2fca1248f01a1136ba",
          "sha256": "232e5e6cb8432645b6205bfd3206d3e29d6ed9acc46eef2ea6d35bd8cd800f3d",
          "sha1": "792540af5d0f3fbaa38a23ff60be49e3a76c6b79",
          "md5": "3de35ebb9843f7bb450fa77a45682f6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-1.0.0-sources.jar",
          "url": "confiant-1.0.0-sources.jar",
          "size": 2815,
          "sha512": "68a567257d51b2b70aef733d20196e6d6d32008907401f0c5e77b46ce2c1bf2e2f472af948ba4a8e6cfd732993bc9ab5148a1efd93a89319634ac419ea253e1c",
          "sha256": "31b9e07a8bcafc0f58892d3f5b1751dffd126140ea324d6880b580d686018fa1",
          "sha1": "0d17f19ff017302a2f2d0c971a32337438397251",
          "md5": "7d344d9deaf50f249598d4c94db9cecd"
        }
      ]
    }
  ]
}
