{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 744876,
          "sha512": "5b5bbf8a0cda17f743dd88a861dc0d4fca87ef6c12ed0a56618b1063ca1e98d5f753a09717f2e9097e916d50f085d5825de931ddd2ee9ac24b92efef3cb88f41",
          "sha256": "35b063f0b3d0346b3a84e77e0b5d6bb8c40e1915134d58a769df8cc99db0f949",
          "sha1": "c024f0971432f73f83f2271751f8ca40ef692247",
          "md5": "6c4ee4c3426aa1fd29eeef5b9242fa0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0.aar",
          "url": "core-1.0.0.aar",
          "size": 744876,
          "sha512": "5b5bbf8a0cda17f743dd88a861dc0d4fca87ef6c12ed0a56618b1063ca1e98d5f753a09717f2e9097e916d50f085d5825de931ddd2ee9ac24b92efef3cb88f41",
          "sha256": "35b063f0b3d0346b3a84e77e0b5d6bb8c40e1915134d58a769df8cc99db0f949",
          "sha1": "c024f0971432f73f83f2271751f8ca40ef692247",
          "md5": "6c4ee4c3426aa1fd29eeef5b9242fa0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.0-sources.jar",
          "url": "core-1.0.0-sources.jar",
          "size": 201239,
          "sha512": "bee561d7bfba8a72dcd5bb23d1aa1f2a28b1995f8d6dac5fb163f97e9dd3126a2da6ff4763e7b563ad3bd064c206626e5a9a89f9e79c8872db69f5ab8bb43a59",
          "sha256": "005967121dc6ee395b20cb136098d490d47287f3df1feb20008ee54fd1c37d86",
          "sha1": "8172c46cfb4d13c53516ceede20f7be670b89114",
          "md5": "bdefb8b3a5b8f997955785f17280c986"
        }
      ]
    }
  ]
}
