{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "confiant-7.2.0.aar",
          "url": "confiant-7.2.0.aar",
          "size": 5543,
          "sha512": "c2de5640f37563e38da629c896785c88b72bf430a59fbc2fce7da60dc4c7a527938a713f966c791da94b957a1e4996e2dcc73d03b54bcf360f58bf8fafc916c8",
          "sha256": "90c49a83c8ebc3eddf1a8a33736fb74c9483722cc951250cf6b48c82d90cb646",
          "sha1": "3e756f89801036564038f2755058112c03a4c7ff",
          "md5": "7c04a4dbf2f771174b39a1110a107fbe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.1-2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-7.2.0.aar",
          "url": "confiant-7.2.0.aar",
          "size": 5543,
          "sha512": "c2de5640f37563e38da629c896785c88b72bf430a59fbc2fce7da60dc4c7a527938a713f966c791da94b957a1e4996e2dcc73d03b54bcf360f58bf8fafc916c8",
          "sha256": "90c49a83c8ebc3eddf1a8a33736fb74c9483722cc951250cf6b48c82d90cb646",
          "sha1": "3e756f89801036564038f2755058112c03a4c7ff",
          "md5": "7c04a4dbf2f771174b39a1110a107fbe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-7.2.0-sources.jar",
          "url": "confiant-7.2.0-sources.jar",
          "size": 3389,
          "sha512": "f6782025a3acf989cf4b9fd289ddf1a607ab2b03c4d25af594cd56fe7f0108ddb6fbd96a2ac66b207b48db85a5c9e564e3acf241c86e8a6776d8db1163711e76",
          "sha256": "8b6d81fc1e9ba1f9a02ee09638c4363d6c08bde48dc9488c728435ee45a78fcc",
          "sha1": "544115d909a7f11799215ba03e254013526fa1ae",
          "md5": "81d9d627d811bf41021dc2f7523d1fb1"
        }
      ]
    }
  ]
}
