{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "confiant-7.2.0.aar",
          "url": "confiant-7.2.0.aar",
          "size": 5544,
          "sha512": "fdaec0de837d31cf957af3931a760c4404ab30ac3631d815fbe30f39caa67c6404e19d3bf52ea4d361c6c29cd7a3fa25a4ff0da0ab9a5683feed89b50fb3f598",
          "sha256": "e665bd8acb03b946bfc4857b30332941cfd24e65ca160e78436758f44edce758",
          "sha1": "d88a7952a8e430a938567a6fb484477eff2b0d40",
          "md5": "2f70e1166fe74bdc09041ee5edde1acc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.1-2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-7.2.0.aar",
          "url": "confiant-7.2.0.aar",
          "size": 5544,
          "sha512": "fdaec0de837d31cf957af3931a760c4404ab30ac3631d815fbe30f39caa67c6404e19d3bf52ea4d361c6c29cd7a3fa25a4ff0da0ab9a5683feed89b50fb3f598",
          "sha256": "e665bd8acb03b946bfc4857b30332941cfd24e65ca160e78436758f44edce758",
          "sha1": "d88a7952a8e430a938567a6fb484477eff2b0d40",
          "md5": "2f70e1166fe74bdc09041ee5edde1acc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-7.2.0-sources.jar",
          "url": "confiant-7.2.0-sources.jar",
          "size": 3389,
          "sha512": "9c4e3f31390b799b1f241c6e2cc8ebde2e84a4af012283f1403cb9cd7ea9945191c0f55bbb04febcade905f080ca077e49b0c42e07f2b8b95afc587b3d91d361",
          "sha256": "fdcdc2e38082ac41259c2dbe70c67bb467a451f00c00a051bb075beea8ee26cf",
          "sha1": "d2f313f3814a975e02bb51d6a2e9d0182f454832",
          "md5": "d016c49f81c63c08be001a817617b756"
        }
      ]
    }
  ]
}
