{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.2.aar",
          "url": "yieldlove-8.2.2.aar",
          "size": 587342,
          "sha512": "98fec3a46c7a4dc87e3d85aadcffd810902238b066c862c47d9f566fd3f59a6f5dc0e45bc5993237cc45dda15a9fc99212635abbc410e1dc713bf9599e840d73",
          "sha256": "a78555788a5798a3db6410aad0a5aa8a6cf79d7dbcc089e803f5b32a4c16fb75",
          "sha1": "1e73aa4c2069493cd2b5cc80ac1432c0c13a6f4a",
          "md5": "bcf309eb479ea5930b307a022af77eb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.2.aar",
          "url": "yieldlove-8.2.2.aar",
          "size": 587342,
          "sha512": "98fec3a46c7a4dc87e3d85aadcffd810902238b066c862c47d9f566fd3f59a6f5dc0e45bc5993237cc45dda15a9fc99212635abbc410e1dc713bf9599e840d73",
          "sha256": "a78555788a5798a3db6410aad0a5aa8a6cf79d7dbcc089e803f5b32a4c16fb75",
          "sha1": "1e73aa4c2069493cd2b5cc80ac1432c0c13a6f4a",
          "md5": "bcf309eb479ea5930b307a022af77eb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.2.2-sources.jar",
          "url": "yieldlove-8.2.2-sources.jar",
          "size": 154732,
          "sha512": "f7b9e65e16dd869fc9dc7b8b60e5e39e8383d91ab1a64d272dfe778cc4e403d451001851743a7836cb576e9c9c8f992a2e8cf1790d3eae82ac5293d49edc20f6",
          "sha256": "d589bda6f20964a06a8616e8a8b3fc7c59eb25817d6a31b64b2d5ce73468bb9e",
          "sha1": "7a2815b4edaa0f8cfff01347e58e97aadb40785f",
          "md5": "2c2d3730ddc0593e37ff721dc89fc78b"
        }
      ]
    }
  ]
}
