{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.1.aar",
          "url": "cmp-8.3.1.aar",
          "size": 28187,
          "sha512": "0373c8f40e76d293b4b9a1d286132b046d3839c6e4465e777f4428ab802315c8af3ed26252011fac14d6a8544ad74cff73be274dabb0b7b8012d8e3a2b0cb35a",
          "sha256": "70ed5617c22f817079fcb1557c93918384a3ba0ba7d59da1ed328870e73833b6",
          "sha1": "2d94d107e8aceabb73f06ec0099fca9a36e7c340",
          "md5": "40af90f3a64c3f9ee7de09ea929ed413"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.3.1.aar",
          "url": "cmp-8.3.1.aar",
          "size": 28187,
          "sha512": "0373c8f40e76d293b4b9a1d286132b046d3839c6e4465e777f4428ab802315c8af3ed26252011fac14d6a8544ad74cff73be274dabb0b7b8012d8e3a2b0cb35a",
          "sha256": "70ed5617c22f817079fcb1557c93918384a3ba0ba7d59da1ed328870e73833b6",
          "sha1": "2d94d107e8aceabb73f06ec0099fca9a36e7c340",
          "md5": "40af90f3a64c3f9ee7de09ea929ed413"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.3.1-sources.jar",
          "url": "cmp-8.3.1-sources.jar",
          "size": 5704,
          "sha512": "4af2e19d6564d57088696ed2696ba3dd5f4738d0867ee4d30627d6719cb2b1f6a4b8a568a4714b799def0c973e8b4a2f18182a320023ebf298092694913703cf",
          "sha256": "47e74b2bee0be90b5a12a19eef603ef42e8917b6396f7d3cfec696d687fcde03",
          "sha1": "ae3db7066bd83000998a05eab9ca56f5ebbffa07",
          "md5": "08d4432dafe9cb2079d20fb4cba276b2"
        }
      ]
    }
  ]
}
