{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.1.aar",
          "url": "yieldlove-8.2.1.aar",
          "size": 587342,
          "sha512": "a64eb06b62fee606f80a8163ee2ad2e2bf60c55cfb6dd1e9d4105d37c2b9df2d29ec01664b61a8ab70945b54c1928e1f3520af8ccb690b8c47b32e2c9a32ce27",
          "sha256": "8e23ba1cf3f5495184599c331ec557570a62f9b89aef9cf5d7f4e3b9c1401481",
          "sha1": "e020937900b226b16c908cb839752b36146bdca1",
          "md5": "2ab8f1fa011f63409baae53b7785a6ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.2.1.aar",
          "url": "yieldlove-8.2.1.aar",
          "size": 587342,
          "sha512": "a64eb06b62fee606f80a8163ee2ad2e2bf60c55cfb6dd1e9d4105d37c2b9df2d29ec01664b61a8ab70945b54c1928e1f3520af8ccb690b8c47b32e2c9a32ce27",
          "sha256": "8e23ba1cf3f5495184599c331ec557570a62f9b89aef9cf5d7f4e3b9c1401481",
          "sha1": "e020937900b226b16c908cb839752b36146bdca1",
          "md5": "2ab8f1fa011f63409baae53b7785a6ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.2.1-sources.jar",
          "url": "yieldlove-8.2.1-sources.jar",
          "size": 154732,
          "sha512": "d1b83f793be6091537e014045447ab0bcb0af5cf19668371ecc7946a6a143d6a36ab2681bfe3cad141314ddfd7c57d0a1886ac3356a6f4c25958a77d5e6be2c8",
          "sha256": "027765886c3d654de606dbbd31016b5efa7738624f690a9ac00ead9cbe5288d0",
          "sha1": "3b6a8d17d706da8a4935be6b1a159aac0d5503d5",
          "md5": "919756c720fb0330bfe0da547ca8bf12"
        }
      ]
    }
  ]
}
