{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "cmp",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0.aar",
          "url": "cmp-1.0.0.aar",
          "size": 28060,
          "sha512": "388d6af2f1494a9a8160b696b717c81362a9029a0258660c4cf2dde2166eab6186f7e4af45f18edaec7ad955846feced0bce872c2cea0e93ec2ca1e0620375f0",
          "sha256": "7f2f4e7f6fe00679f2b977ba9e54568f573e29c04fc67dcbd4a9c865bcbd7335",
          "sha1": "c708e3cce9f1518217fad7200841d4f76a3e6fbc",
          "md5": "9cbac00393d4ef9302a776fc1a46911d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0.aar",
          "url": "cmp-1.0.0.aar",
          "size": 28060,
          "sha512": "388d6af2f1494a9a8160b696b717c81362a9029a0258660c4cf2dde2166eab6186f7e4af45f18edaec7ad955846feced0bce872c2cea0e93ec2ca1e0620375f0",
          "sha256": "7f2f4e7f6fe00679f2b977ba9e54568f573e29c04fc67dcbd4a9c865bcbd7335",
          "sha1": "c708e3cce9f1518217fad7200841d4f76a3e6fbc",
          "md5": "9cbac00393d4ef9302a776fc1a46911d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-1.0.0-sources.jar",
          "url": "cmp-1.0.0-sources.jar",
          "size": 5280,
          "sha512": "49bbd6fff67721d142016640aa20e1ef841ca74217963996f993b9f958a3518f56a7d010acbc38e59767673a47bdda20f5a4dea00689f6ab0a86e4c2cb0ae351",
          "sha256": "e6eeb6d02ca5e00d9425379d16a7a777079b7f4041502ceeb4c91548b11012cf",
          "sha1": "4829d592e0a0f7c4c089f95a579e6f9762576cfd",
          "md5": "7dd8fe9e229c7c6b01fa3c3b1ec92d3f"
        }
      ]
    }
  ]
}
