{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.0.0.aar",
          "url": "compose-0.0.0.aar",
          "size": 45850,
          "sha512": "b385493d354ed266a85b0d90c95ba4f33810c28914196b80fe599347406787063ecd8c91833856339d1d998c554535ed9e1ffcca9a4a69f3ec66b0381db267cf",
          "sha256": "1daeaa8407c0de621c25290b667e1152b2aee4fe83531a62dc7f6edf598c05ff",
          "sha1": "b7d0b1d35f31cce4705dbe29d8ea785913c3439b",
          "md5": "d7dcc82ff2709f0f180812f1e6f75975"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.0.0.aar",
          "url": "compose-0.0.0.aar",
          "size": 45850,
          "sha512": "b385493d354ed266a85b0d90c95ba4f33810c28914196b80fe599347406787063ecd8c91833856339d1d998c554535ed9e1ffcca9a4a69f3ec66b0381db267cf",
          "sha256": "1daeaa8407c0de621c25290b667e1152b2aee4fe83531a62dc7f6edf598c05ff",
          "sha1": "b7d0b1d35f31cce4705dbe29d8ea785913c3439b",
          "md5": "d7dcc82ff2709f0f180812f1e6f75975"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-0.0.0-sources.jar",
          "url": "compose-0.0.0-sources.jar",
          "size": 9104,
          "sha512": "af17236d7386051a01884c11e78cf9fbeca178dc53a1b6723280b5f0518b43f6e2a4ed3a555c8a745f82156949f1570c90e70d995e870f8ea3b8e9ce0104f36e",
          "sha256": "35ba95c1dc2e373e345025b3b1449bbcb33c90133c018a07f56abd26cbb84b09",
          "sha1": "90d8538bddf5532b80cedefe8a66f58d0c9b62be",
          "md5": "a130909c0f6a46b6e200f7a5276b113a"
        }
      ]
    }
  ]
}
