{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.0.0.aar",
          "url": "compose-0.0.0.aar",
          "size": 43963,
          "sha512": "825e0591853f48687b6bdfae4445369e10fc770a41f31ebd1436e7b739dfbf70f7cb1ee1fe06cb5ccd06b8897f2082987a58374dd4e0d29b6b3fec05f23e86ac",
          "sha256": "b17bdcea56566f53ba0b426c9f47c6573e9ee5c71522170f97589b69ace15c22",
          "sha1": "5ad84941a3cddde2143066c0f601d0d41d0ad3a9",
          "md5": "d5ee202e94d4f545450f8c8661bf8a75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.0.0.aar",
          "url": "compose-0.0.0.aar",
          "size": 43963,
          "sha512": "825e0591853f48687b6bdfae4445369e10fc770a41f31ebd1436e7b739dfbf70f7cb1ee1fe06cb5ccd06b8897f2082987a58374dd4e0d29b6b3fec05f23e86ac",
          "sha256": "b17bdcea56566f53ba0b426c9f47c6573e9ee5c71522170f97589b69ace15c22",
          "sha1": "5ad84941a3cddde2143066c0f601d0d41d0ad3a9",
          "md5": "d5ee202e94d4f545450f8c8661bf8a75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-0.0.0-sources.jar",
          "url": "compose-0.0.0-sources.jar",
          "size": 9104,
          "sha512": "5c21421a3f786121ba110b3526915dc4c816eaeaef9485bd9053231b68508370ab265f1e6da4de912747f40bee60a4fa792aba0d3c44c048c9f1865aa7a0fb61",
          "sha256": "486c81781bcf025d3d7b38b3583cea37c8ea47575ad78b2efddabed473842e80",
          "sha1": "36c60510001a40a9e215e6041e69e73eb724cd20",
          "md5": "961f35397d363ef676aeef13fab2e24b"
        }
      ]
    }
  ]
}
