{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5516,
          "sha512": "994f7ef185f159a49d7178bb506673865786a933913b830079fa8d17a12c72ecc70594cb9df838b40fc34fa28ddd668a4f31e4cd031ee18e4a29ed7aca04350b",
          "sha256": "883dcbbe3cdc68e68eb9a4c07ec104ae1edfc2940857b28cb2cd5d5d856c7c59",
          "sha1": "cf91a46cf4b105945f00bfddac6641aba54ed48c",
          "md5": "846081d7b654ac1408e06eb79e0b33a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5516,
          "sha512": "994f7ef185f159a49d7178bb506673865786a933913b830079fa8d17a12c72ecc70594cb9df838b40fc34fa28ddd668a4f31e4cd031ee18e4a29ed7aca04350b",
          "sha256": "883dcbbe3cdc68e68eb9a4c07ec104ae1edfc2940857b28cb2cd5d5d856c7c59",
          "sha1": "cf91a46cf4b105945f00bfddac6641aba54ed48c",
          "md5": "846081d7b654ac1408e06eb79e0b33a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.0.0-sources.jar",
          "url": "confiant-8.0.0-sources.jar",
          "size": 3388,
          "sha512": "80a0a8c6e9ff3773851d1be9fbd8bdeace9d8105179ea41c66e9fc12b4f19eeb566c196a36dccb5d648f80a861696e99a22252fc6a58add124f7cd7101a5773e",
          "sha256": "bf7d5ba3169a0ef47ac9a14de60edd1d8af9333822886a8d81dd8c9499ef4e3d",
          "sha1": "04da1398e665e7cc7eaa0c72aa01290437ae4e51",
          "md5": "8f8e14079e148c2f866a37bea872da57"
        }
      ]
    }
  ]
}
