{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5515,
          "sha512": "3750dc20350fee19f3c532831230f1bb8f555a5935757054632d689de6c7d570aa2568c22fa5199b4778c1358529755c75e175cc7faa7e1b2ba3bd31adbc8770",
          "sha256": "c9686fae41386e387d4a06bf6974bb3ac6263ed559df809d949df175c20b00ec",
          "sha1": "40be3ad4f724d04acb7719561661faa9dfa25644",
          "md5": "8eb2a10abe2569a5320d6bd687d15a51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5515,
          "sha512": "3750dc20350fee19f3c532831230f1bb8f555a5935757054632d689de6c7d570aa2568c22fa5199b4778c1358529755c75e175cc7faa7e1b2ba3bd31adbc8770",
          "sha256": "c9686fae41386e387d4a06bf6974bb3ac6263ed559df809d949df175c20b00ec",
          "sha1": "40be3ad4f724d04acb7719561661faa9dfa25644",
          "md5": "8eb2a10abe2569a5320d6bd687d15a51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.0.0-sources.jar",
          "url": "confiant-8.0.0-sources.jar",
          "size": 3389,
          "sha512": "d7445ff9806eef1cc267e7b17b51288e850934be1e79aa7c1e672453705eb8be7f1bbab1cc54fc91c4fd208fec688c42bac4722529f98ab761f936d342da4096",
          "sha256": "0841c6482601b36caf6fd7e9eb1f3c0e08bb58eb8220a2073038243a57201945",
          "sha1": "93adaf1bc5bc5b3d78c7e57d3d986a7340dc0355",
          "md5": "3cb57c8cfb1afadd194da95e4d7fbeb5"
        }
      ]
    }
  ]
}
