{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5514,
          "sha512": "c8210a255c1dd1b3f7e59f6c972e7dd8e2210dabfb51330e7673b5c7e7f5507cb6f52f342ba88325453a7aac950b9a5a8378304d347bb0b25fe8293ed7fad8e8",
          "sha256": "fd0c4518cef0520cdafee0b3a54a6898843cc8a1031bff779e38e5bd06b721ff",
          "sha1": "0f8318a3a367233dfd7aa1637b1a0fcebd99ffd0",
          "md5": "5f0224ce9f9825d370abac141c4a60af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.0.0.aar",
          "url": "confiant-8.0.0.aar",
          "size": 5514,
          "sha512": "c8210a255c1dd1b3f7e59f6c972e7dd8e2210dabfb51330e7673b5c7e7f5507cb6f52f342ba88325453a7aac950b9a5a8378304d347bb0b25fe8293ed7fad8e8",
          "sha256": "fd0c4518cef0520cdafee0b3a54a6898843cc8a1031bff779e38e5bd06b721ff",
          "sha1": "0f8318a3a367233dfd7aa1637b1a0fcebd99ffd0",
          "md5": "5f0224ce9f9825d370abac141c4a60af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.0.0-sources.jar",
          "url": "confiant-8.0.0-sources.jar",
          "size": 3388,
          "sha512": "972c8d1a52e78ef5ad334e66b44ae0ca3637f0ca936267485eb023d56fe026b478115248eb1ff2f9a7f4ccfc54473fe9d90d5c8e2e2f1c28d3c553e8fed5dec5",
          "sha256": "651ac17a90d403c3bf120d1ced44728296f9a057f4a52392f0c1e1b6e06ea469",
          "sha1": "46a9cd4bcf2831d48f9ef98c4ed6bfd87c49d24f",
          "md5": "3c103a73d7f2322373c4482715496b0e"
        }
      ]
    }
  ]
}
