{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cmp-7.2.0.aar",
          "url": "cmp-7.2.0.aar",
          "size": 8946,
          "sha512": "eb0ec913cc7b2324d54f9b616612bc5d9288a83d73a258a89b18cbba1973134b6f549f637a86344aa3a1172bb0b796cee41761a5e75ce03bc147b558d573bb0c",
          "sha256": "f379fd18d631b61eeaee29148884db5c2bbdbdcb2e266a92a7cb792334bb9c65",
          "sha1": "68f9882ee4b532b5d124915d998141b1a60bb20a",
          "md5": "3212366727bba6dc3f5189ea68cd5596"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-7.2.0.aar",
          "url": "cmp-7.2.0.aar",
          "size": 8946,
          "sha512": "eb0ec913cc7b2324d54f9b616612bc5d9288a83d73a258a89b18cbba1973134b6f549f637a86344aa3a1172bb0b796cee41761a5e75ce03bc147b558d573bb0c",
          "sha256": "f379fd18d631b61eeaee29148884db5c2bbdbdcb2e266a92a7cb792334bb9c65",
          "sha1": "68f9882ee4b532b5d124915d998141b1a60bb20a",
          "md5": "3212366727bba6dc3f5189ea68cd5596"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-7.2.0-sources.jar",
          "url": "cmp-7.2.0-sources.jar",
          "size": 4928,
          "sha512": "a09979a71430d3b511caa8a2d64467da102a46185b03825006357cf8912661bc1a70ec42d707273f467ec8b0d301544bb81d09310e10bba1e284582312fd0606",
          "sha256": "e0e28807d7ecd4db982b35d57bc209b4c58638944402260eb97c89b0ed5554d4",
          "sha1": "787635da993ccf2c014e19d739ae6bbee6ad85e4",
          "md5": "41eda5f210d1b687ad7c5b284ab2ce17"
        }
      ]
    }
  ]
}
