{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "7.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cmp-7.2.0.aar",
          "url": "cmp-7.2.0.aar",
          "size": 8946,
          "sha512": "5a9fa8024b019dcc2fddf1c30da79d2c2416c8a06a202b61c377cd74eef3c66b67b8c3329ed6e659f8f7e8dbc216a96566a26a51b8e0eb520ec37114d189bb55",
          "sha256": "f83085030e0867ed9d41fea2a189737667d9f173d507be5dcb19e6c1161301bf",
          "sha1": "41fac0e700b6fdd777cace9682675942b651bcdc",
          "md5": "3ee373f8988e66b42db35d1c78a72758"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-7.2.0.aar",
          "url": "cmp-7.2.0.aar",
          "size": 8946,
          "sha512": "5a9fa8024b019dcc2fddf1c30da79d2c2416c8a06a202b61c377cd74eef3c66b67b8c3329ed6e659f8f7e8dbc216a96566a26a51b8e0eb520ec37114d189bb55",
          "sha256": "f83085030e0867ed9d41fea2a189737667d9f173d507be5dcb19e6c1161301bf",
          "sha1": "41fac0e700b6fdd777cace9682675942b651bcdc",
          "md5": "3ee373f8988e66b42db35d1c78a72758"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-7.2.0-sources.jar",
          "url": "cmp-7.2.0-sources.jar",
          "size": 4928,
          "sha512": "739664e2650bb1594ede79baacd962372bea8419c0c1d4898f8426faee7369b6d08f1e18d059665addeaa51c5c4c55415652f14e1a5f86fa6e6634ee26442d9c",
          "sha256": "c9edd4afc1af721cfe278dcebf335073395f7a52fae09d02955d0ebc1512f95e",
          "sha1": "1ed8a28291b8ed3535165a712e5a827bee84645c",
          "md5": "03c4a892fd05f41f07c735d4ae3e2955"
        }
      ]
    }
  ]
}
