{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 24132,
          "sha512": "0058ef84867b49c9e3ec5239550afcb379d4fcccc24f7143993deb65044016d49338bf46db91267c57161689e7e3bc932eb70b28ebeb8d0b5afc2d59e16b15d2",
          "sha256": "57a331a68875ec9128e56531d225ed3b1108f850e3c5a5b6556df0fd58d5e9cb",
          "sha1": "be5b7596a7d1ea8e7f208e8358fafd55458870d3",
          "md5": "c6a12a42137f2e5863c67c1575ff9de9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.9"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 24132,
          "sha512": "0058ef84867b49c9e3ec5239550afcb379d4fcccc24f7143993deb65044016d49338bf46db91267c57161689e7e3bc932eb70b28ebeb8d0b5afc2d59e16b15d2",
          "sha256": "57a331a68875ec9128e56531d225ed3b1108f850e3c5a5b6556df0fd58d5e9cb",
          "sha1": "be5b7596a7d1ea8e7f208e8358fafd55458870d3",
          "md5": "c6a12a42137f2e5863c67c1575ff9de9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.0.0-sources.jar",
          "url": "cmp-8.0.0-sources.jar",
          "size": 5915,
          "sha512": "ee99590e763d44b4ba4272d875b17e36cc9e517725beebdddeed73399f724627f42fda4b9a4689fdc4295a067c7585db9d5170e95fb4192da6fb30926ae5b096",
          "sha256": "116dd3f8836a02862fc062435ee8cc55106ab83df4bb341433a915846340c3de",
          "sha1": "4aecd1770b47ac171c7cf29985374b9b9098c7cf",
          "md5": "440eb7dddb3445e9f84969d9d1a6cead"
        }
      ]
    }
  ]
}
