{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 23608,
          "sha512": "28cbd466b829c7a44ddb5f09077999f7e2504bfe20f079c406be25b4882acbbb6d27427bb68591d7db1848638bb31579d6d102c83f0be588699bc7f9dfd5c34c",
          "sha256": "fc5fe9a785881bc9ce12500e3a85a044993798fdf8e7276406f966c0c8a41932",
          "sha1": "be0c30df07382edb7657e8338cdf81e79502fd5f",
          "md5": "87528f04323a82abac2fe053003037d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.9"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 23608,
          "sha512": "28cbd466b829c7a44ddb5f09077999f7e2504bfe20f079c406be25b4882acbbb6d27427bb68591d7db1848638bb31579d6d102c83f0be588699bc7f9dfd5c34c",
          "sha256": "fc5fe9a785881bc9ce12500e3a85a044993798fdf8e7276406f966c0c8a41932",
          "sha1": "be0c30df07382edb7657e8338cdf81e79502fd5f",
          "md5": "87528f04323a82abac2fe053003037d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.0.0-sources.jar",
          "url": "cmp-8.0.0-sources.jar",
          "size": 5533,
          "sha512": "cb0a4989c7f4d732146407d433ebe7bc0d0e82e0a123035920e72b940b44fc5a70e47dd069bf40a13b2cb51c9d20648d98df39ec77091967f88372b7a631d731",
          "sha256": "fe3199d4261d7f7b993e60ce48427b2a797a08cd433a9f2592fcdc2763b48361",
          "sha1": "6a407855d93c9e877ed3bf59c996107a64b1e940",
          "md5": "c78c9a491700a5c0cd5f3e9975468958"
        }
      ]
    }
  ]
}
