{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 23609,
          "sha512": "d6756977469a891cb9a378813a961baf3e519f3e8f1cf63608db89c5ef1a450700bd765458f7b56e4e81aa64295d0d7baba68141110e70a24f7c9a99551bec2d",
          "sha256": "3f1dee83defc0d454d126dbcd1569ebf77c67f696bf6045a120feed690cf1de6",
          "sha1": "a5ac05b0ef29d47d42662844ad59e2ebb5de74b4",
          "md5": "690e9f2691793017ea5dc7261ebecde3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.9"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.0.aar",
          "url": "cmp-8.0.0.aar",
          "size": 23609,
          "sha512": "d6756977469a891cb9a378813a961baf3e519f3e8f1cf63608db89c5ef1a450700bd765458f7b56e4e81aa64295d0d7baba68141110e70a24f7c9a99551bec2d",
          "sha256": "3f1dee83defc0d454d126dbcd1569ebf77c67f696bf6045a120feed690cf1de6",
          "sha1": "a5ac05b0ef29d47d42662844ad59e2ebb5de74b4",
          "md5": "690e9f2691793017ea5dc7261ebecde3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.0.0-sources.jar",
          "url": "cmp-8.0.0-sources.jar",
          "size": 5533,
          "sha512": "6328d7da9649f1d89bb2285ae7751cc8f32885f9460eeb5d85c83ab1865e4d4d7a39d6eb715e2cf080086ef831ccc8df87f4944e3070b27caea8e7a45dc23617",
          "sha256": "d54111d7ebfd465612781817bdc65c04f8449b7b2128b9096835eb2284b4aa39",
          "sha1": "4253bc2594f5cfe112a1da9e5b3a92517a87c1c2",
          "md5": "adbff25fedc5fc84b12e8ba7e588ce51"
        }
      ]
    }
  ]
}
