{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "compose",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.1.aar",
          "url": "compose-8.3.1.aar",
          "size": 44045,
          "sha512": "929865acca42561542a909c1b502501d19c57fd4e639b0207389aeeb3075868fef2dd9dd900bba4c4e72bce96ed71ee8e7d912ea90f8a973b3d7106f630c4df9",
          "sha256": "ebc4005fd7397b684de0bd9e988500c62adee936d2cf71f39062158847a2b9a7",
          "sha1": "c67596ace665d8d60c05e19eadcb4ad3418984bf",
          "md5": "0a36f8658e9487b9e4171f4e8427c4f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.1.aar",
          "url": "compose-8.3.1.aar",
          "size": 44045,
          "sha512": "929865acca42561542a909c1b502501d19c57fd4e639b0207389aeeb3075868fef2dd9dd900bba4c4e72bce96ed71ee8e7d912ea90f8a973b3d7106f630c4df9",
          "sha256": "ebc4005fd7397b684de0bd9e988500c62adee936d2cf71f39062158847a2b9a7",
          "sha1": "c67596ace665d8d60c05e19eadcb4ad3418984bf",
          "md5": "0a36f8658e9487b9e4171f4e8427c4f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-8.3.1-sources.jar",
          "url": "compose-8.3.1-sources.jar",
          "size": 9152,
          "sha512": "bc86a3424488c12f8e902465acdcbe44dbb74749f5c88d299ce44e4f838814dcbc26fea9bed3999696d5c3f9dfe1355e301e261c0a0010f8fde23ae162e46852",
          "sha256": "311803d318ea2ebf111c5cd70e7f2713ee1511b53ccd8aabbeeebc977766a4bb",
          "sha1": "9dcfbefccd45cf6e2d452d3688027f4e32cd597d",
          "md5": "7e1fadc408d30778626d23bac04632c6"
        }
      ]
    }
  ]
}
