{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "compose",
    "version": "8.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.1.aar",
          "url": "compose-8.3.1.aar",
          "size": 44043,
          "sha512": "0effc72f3bfa70d3bafb0e3659282c8ea373e1027aa3c0273a8333abd582d6ea2dc23dcfd657312cd34eb1e4c57ec0889385bd56e7b36623d18f41a9b6758769",
          "sha256": "576fd7f4b0e016f3a26bf02685462f4392a2fd94fa67e30cafbc8606e4cd2198",
          "sha1": "5654ede2b11bd34c484762da777fc11980648769",
          "md5": "2073f4c19132c596582affb2364bc3b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-8.3.1.aar",
          "url": "compose-8.3.1.aar",
          "size": 44043,
          "sha512": "0effc72f3bfa70d3bafb0e3659282c8ea373e1027aa3c0273a8333abd582d6ea2dc23dcfd657312cd34eb1e4c57ec0889385bd56e7b36623d18f41a9b6758769",
          "sha256": "576fd7f4b0e016f3a26bf02685462f4392a2fd94fa67e30cafbc8606e4cd2198",
          "sha1": "5654ede2b11bd34c484762da777fc11980648769",
          "md5": "2073f4c19132c596582affb2364bc3b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-8.3.1-sources.jar",
          "url": "compose-8.3.1-sources.jar",
          "size": 9152,
          "sha512": "2a6b8bad33f662d89622c26854ae4c8535907f703474128dcfd404885959ec85fdddd4545dd2a84b48685495e9dc40166ae2ce0522e419518338088af9ab29e1",
          "sha256": "1c185a2d8789104372324e2fc8e89f60e1eb9b148b30d782a70e7b36da449f7c",
          "sha1": "85fa980e0e4b15b408ff4073b41a2eda07b234ef",
          "md5": "c8f78be82a8614fa1cd32a07c34e2f08"
        }
      ]
    }
  ]
}
