{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.0.aar",
          "url": "confiant-8.2.0.aar",
          "size": 6592,
          "sha512": "97ecea52b4aa5df5472e9dc4f0a0f19f3b3922b894fe268fb1f42137dc716442442ed2643b3fa65dd3c55e3d2f83fab10948accfad961ef9b3ba924e975c6e5a",
          "sha256": "e454026b29980a3740e6659135ecd43d47789c964362bc5959f0d75c9a67b796",
          "sha1": "5f4c5debd0d9490cc6464bf6ab1614d65f8514a6",
          "md5": "c2592b6dea2a07c47061f50183b448b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.0.aar",
          "url": "confiant-8.2.0.aar",
          "size": 6592,
          "sha512": "97ecea52b4aa5df5472e9dc4f0a0f19f3b3922b894fe268fb1f42137dc716442442ed2643b3fa65dd3c55e3d2f83fab10948accfad961ef9b3ba924e975c6e5a",
          "sha256": "e454026b29980a3740e6659135ecd43d47789c964362bc5959f0d75c9a67b796",
          "sha1": "5f4c5debd0d9490cc6464bf6ab1614d65f8514a6",
          "md5": "c2592b6dea2a07c47061f50183b448b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.2.0-sources.jar",
          "url": "confiant-8.2.0-sources.jar",
          "size": 3245,
          "sha512": "6c2ad6afa9b0127e56f37c7d56d0c9eaa7bb852eeef3dd182734353262cdce230f28aa817ce790cf1893932d34e1dbba76562e58342e09a29b301f5be43d0ed0",
          "sha256": "63d5695ac5dd2066ba87eb5b18aa60309ed2f2a7ab0637e5ff8d98f672d08a6d",
          "sha1": "8912993eae1752d9cab82165acce29b26754fd81",
          "md5": "d33e34b13d519aae85bfa5f11442bc3e"
        }
      ]
    }
  ]
}
