{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "confiant",
    "version": "8.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.0.aar",
          "url": "confiant-8.2.0.aar",
          "size": 6586,
          "sha512": "4d84133c2fe789883145a54b63e5881dd5a3e21900825967f193f383c3e9fdc551851b858ec65c41744abf72f714f1da33876b165e223a310f5bc81f7f6563f7",
          "sha256": "83a3df4456610b0fe22f7d403a748dcce768bb777d066ab8288585d517bed8be",
          "sha1": "77c07f4400695015c9635eaa82bda222fa0d9d8a",
          "md5": "a707dad05207e65c814297d391853f3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-8.2.0.aar",
          "url": "confiant-8.2.0.aar",
          "size": 6586,
          "sha512": "4d84133c2fe789883145a54b63e5881dd5a3e21900825967f193f383c3e9fdc551851b858ec65c41744abf72f714f1da33876b165e223a310f5bc81f7f6563f7",
          "sha256": "83a3df4456610b0fe22f7d403a748dcce768bb777d066ab8288585d517bed8be",
          "sha1": "77c07f4400695015c9635eaa82bda222fa0d9d8a",
          "md5": "a707dad05207e65c814297d391853f3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-8.2.0-sources.jar",
          "url": "confiant-8.2.0-sources.jar",
          "size": 3245,
          "sha512": "6c2ad6afa9b0127e56f37c7d56d0c9eaa7bb852eeef3dd182734353262cdce230f28aa817ce790cf1893932d34e1dbba76562e58342e09a29b301f5be43d0ed0",
          "sha256": "63d5695ac5dd2066ba87eb5b18aa60309ed2f2a7ab0637e5ff8d98f672d08a6d",
          "sha1": "8912993eae1752d9cab82165acce29b26754fd81",
          "md5": "d33e34b13d519aae85bfa5f11442bc3e"
        }
      ]
    }
  ]
}
