{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "cmp",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-0.0.0.aar",
          "url": "cmp-0.0.0.aar",
          "size": 28110,
          "sha512": "192706331f559beef9e6b44be5b23033640f2f297c6998fd1fcf0a1fc34609f471ab8b0742289d331c82d85157a6ba5f4f6016ce3edbb5510a38985157b580cb",
          "sha256": "266b952b3b827c3a5d1d0940b2f760e9479414f754f9c29812e554cff1ba36c6",
          "sha1": "e90cf3d381119731bd41d03358688d667aab354b",
          "md5": "e26aa6904ee86421c5f1335c00e066f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-0.0.0.aar",
          "url": "cmp-0.0.0.aar",
          "size": 28110,
          "sha512": "192706331f559beef9e6b44be5b23033640f2f297c6998fd1fcf0a1fc34609f471ab8b0742289d331c82d85157a6ba5f4f6016ce3edbb5510a38985157b580cb",
          "sha256": "266b952b3b827c3a5d1d0940b2f760e9479414f754f9c29812e554cff1ba36c6",
          "sha1": "e90cf3d381119731bd41d03358688d667aab354b",
          "md5": "e26aa6904ee86421c5f1335c00e066f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-0.0.0-sources.jar",
          "url": "cmp-0.0.0-sources.jar",
          "size": 5280,
          "sha512": "aeb2ddd2b377d292bca6568259a64cecda9ed9428515302fa8398e161743fc86ce6aaa47083343049d37937596c234ee05efacdfb52cf075f6f911f4e6759a7f",
          "sha256": "d8b9c241b971f9f8f0924250e7a220bb2ba46de5f9550fa97bb54399680d2884",
          "sha1": "331bde5b455aa48bb8b99d19ba518bbd7f3e9fd4",
          "md5": "1bd107b226a7e910035d7f711e50a0ba"
        }
      ]
    }
  ]
}
