{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "cmp",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-0.0.0.aar",
          "url": "cmp-0.0.0.aar",
          "size": 28112,
          "sha512": "ff10cc00907ed4c596d51ec244abf672bdd6c2c9427af2ae07c14eace57428dc96b6fd8ccff4cbafc1ecd30cd8e6775e239da389c459f34d43cfdad0d0304623",
          "sha256": "46831528a42cbfe9b14604c5c6fc7ad70d23eeee33de2632d13b06d62308847b",
          "sha1": "e6a4fa164775f5259d7d28312e12a2adc3b2829f",
          "md5": "32a2c76a3e01db521e582528adc77e2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-0.0.0.aar",
          "url": "cmp-0.0.0.aar",
          "size": 28112,
          "sha512": "ff10cc00907ed4c596d51ec244abf672bdd6c2c9427af2ae07c14eace57428dc96b6fd8ccff4cbafc1ecd30cd8e6775e239da389c459f34d43cfdad0d0304623",
          "sha256": "46831528a42cbfe9b14604c5c6fc7ad70d23eeee33de2632d13b06d62308847b",
          "sha1": "e6a4fa164775f5259d7d28312e12a2adc3b2829f",
          "md5": "32a2c76a3e01db521e582528adc77e2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-0.0.0-sources.jar",
          "url": "cmp-0.0.0-sources.jar",
          "size": 5280,
          "sha512": "988d39dfef4bd5ac97707c05552c8ed11a45dbd930614cb31d73c57dc16a7e9342684f0f967f823b5400bc2b2a12fb1d7c4d8ac81b4de8ea1c000aa24aa40748",
          "sha256": "29394d75a3e91ab57e874fba54ee39074420c628588e33557f407e8a447d4ef8",
          "sha1": "9ddbb9d61f698df740616eb9d46553f6a5d0d8cc",
          "md5": "fee6505042c81fdd283d35dbd56ed13d"
        }
      ]
    }
  ]
}
