{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.0.0.aar",
          "url": "gravite-8.0.0.aar",
          "size": 15444,
          "sha512": "4d6a379e7f20e5405cc2abe51155b9f540dfd0f88d17754809a6166a1e3d2a1536b92b5e3098cce8322e5044904a40e094172a320aa56afc36123349ce38435a",
          "sha256": "c090eea7cad083d9d61bcde8056a50f704f01d9314bd38c4eff4c38abc110c13",
          "sha1": "958e6d259d5f7984bef347b776669d6842d0a140",
          "md5": "84482f9287967748908de0d0a80ad0db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.14.3"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.0.0.aar",
          "url": "gravite-8.0.0.aar",
          "size": 15444,
          "sha512": "4d6a379e7f20e5405cc2abe51155b9f540dfd0f88d17754809a6166a1e3d2a1536b92b5e3098cce8322e5044904a40e094172a320aa56afc36123349ce38435a",
          "sha256": "c090eea7cad083d9d61bcde8056a50f704f01d9314bd38c4eff4c38abc110c13",
          "sha1": "958e6d259d5f7984bef347b776669d6842d0a140",
          "md5": "84482f9287967748908de0d0a80ad0db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-8.0.0-sources.jar",
          "url": "gravite-8.0.0-sources.jar",
          "size": 10528,
          "sha512": "230157d5eff53b5da8c125e4502c03400dd3439d8fa55bbf635079648846c5e15e4d87f250029047ebb076979a72c67a3d8768200b4c14ab7d41bfa81eaeac48",
          "sha256": "44726311a9287f70cba018fa429d8caa9f79a3d30a5a94f54e49c2a7fc5d0055",
          "sha1": "09f3f60390762888d83462078703cb45533d3592",
          "md5": "2bf3763a8cc908b75f5361697b048dae"
        }
      ]
    }
  ]
}
