{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "gravite",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.0.0.aar",
          "url": "gravite-8.0.0.aar",
          "size": 15448,
          "sha512": "7de5491dddc185b5fbea01465aa8f8b31fb96ee9ed2d77b7f1c0cfe77774d0e16e935d7e971c3ad46aed3e37b9dc016ce36bc96725ffa77cc59561b93b409204",
          "sha256": "fbf2b2ea02b6926e6e30b4fdd9e3c4eb62d227f7dca01c67753cb0878f8a4779",
          "sha1": "c1fe33090715bc96b6ce131fa91cdf83610bed99",
          "md5": "64ba640ddbd136e1ec2ac1f5effccf71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.intentsoftware.addapptr",
          "module": "AATKit",
          "version": {
            "requires": "3.14.3"
          },
          "excludes": [
            {
              "group": "com.applovin",
              "module": "applovin-sdk"
            },
            {
              "group": "com.mbridge.msdk.oversea",
              "module": "*"
            },
            {
              "group": "com.rtb.sdk",
              "module": "RTB-SDK"
            },
            {
              "group": "co.ogury",
              "module": "ogury-sdk"
            },
            {
              "group": "com.feedad.android",
              "module": "feedad-sdk"
            },
            {
              "group": "com.smaato.android.sdk",
              "module": "*"
            },
            {
              "group": "com.criteo.publisher",
              "module": "criteo-publisher-sdk"
            },
            {
              "group": "org.prebid",
              "module": "prebid-mobile-sdk"
            },
            {
              "group": "com.vungle",
              "module": "vungle-ads"
            },
            {
              "group": "net.pubnative",
              "module": "hybid.sdk"
            },
            {
              "group": "com.inmobi.monetization",
              "module": "inmobi-ads-kotlin"
            },
            {
              "group": "com.appnexus.opensdk",
              "module": "appnexus-sdk"
            },
            {
              "group": "com.equativ.android",
              "module": "equativ-display-sdk"
            },
            {
              "group": "com.unity3d.ads",
              "module": "unity-ads"
            },
            {
              "group": "com.google.ads.mediation",
              "module": "facebook"
            },
            {
              "group": "com.tappx.sdk.android",
              "module": "tappx-sdk"
            },
            {
              "group": "com.intentsoftware.addapptr.subsdk",
              "module": "AdColony"
            },
            {
              "group": "com.ironsource.sdk",
              "module": "mediationsdk"
            },
            {
              "group": "com.yoc.visx.sdk",
              "module": "visx-sdk"
            }
          ]
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "gravite-8.0.0.aar",
          "url": "gravite-8.0.0.aar",
          "size": 15448,
          "sha512": "7de5491dddc185b5fbea01465aa8f8b31fb96ee9ed2d77b7f1c0cfe77774d0e16e935d7e971c3ad46aed3e37b9dc016ce36bc96725ffa77cc59561b93b409204",
          "sha256": "fbf2b2ea02b6926e6e30b4fdd9e3c4eb62d227f7dca01c67753cb0878f8a4779",
          "sha1": "c1fe33090715bc96b6ce131fa91cdf83610bed99",
          "md5": "64ba640ddbd136e1ec2ac1f5effccf71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gravite-8.0.0-sources.jar",
          "url": "gravite-8.0.0-sources.jar",
          "size": 10528,
          "sha512": "ff58a4cd05638868d615951c8aebeae2f294c526d901598432eff86f8ed391846ae320150c2960a52b12cdacb2c0abd4d79d004eb378bcd058841e0bef0ae343",
          "sha256": "e45d2d034324d54bcff15126b1458e2d572484ea20dc65406233b3b123da9c76",
          "sha1": "e855960fe21fca18bcf30b0f4ea099be042e025c",
          "md5": "db3b52196c1e0a91169c40154d402c86"
        }
      ]
    }
  ]
}
