{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.1.1.aar",
          "url": "yieldlove-7.1.1.aar",
          "size": 353996,
          "sha512": "5c656f3b9e0f48fa846ea767f142182c8577eb8a955f0f1d40a90bf8d5879aa38fb19f1560fc1d4d7d0f08e29b5c41f659776412ee971aea1838406a05b9bc80",
          "sha256": "5d757937f968e5bba2c03d21e281ad0b0e47cda92930dc328ff6bb25c8c666ae",
          "sha1": "8a05a3b882c05924b838fca279c3be17217a7937",
          "md5": "b2eb2c695ca0a09e59b27f40a7af95ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-7.1.1.aar",
          "url": "yieldlove-7.1.1.aar",
          "size": 353996,
          "sha512": "5c656f3b9e0f48fa846ea767f142182c8577eb8a955f0f1d40a90bf8d5879aa38fb19f1560fc1d4d7d0f08e29b5c41f659776412ee971aea1838406a05b9bc80",
          "sha256": "5d757937f968e5bba2c03d21e281ad0b0e47cda92930dc328ff6bb25c8c666ae",
          "sha1": "8a05a3b882c05924b838fca279c3be17217a7937",
          "md5": "b2eb2c695ca0a09e59b27f40a7af95ca"
        }
      ]
    }
  ]
}
