{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.2.aar",
          "url": "cmp-8.0.2.aar",
          "size": 24135,
          "sha512": "3a8b655c0f90c29e45005e5f5154b68f07bc9101348a96418cf516cdf86286b1b9d9f6ef00f3cd8888daf66016184b5be64c7a2472f84af9ad9390f2dc40d976",
          "sha256": "e286b8e1114a10270d4db93df0252b57ba26eefd84d4f237dcf47f44908845b5",
          "sha1": "3b705f645a383bfbe5c1a1e7780d45c3628f2e32",
          "md5": "ed1328a1b54dc1d5c358192fc0b15195"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.9"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.0.2.aar",
          "url": "cmp-8.0.2.aar",
          "size": 24135,
          "sha512": "3a8b655c0f90c29e45005e5f5154b68f07bc9101348a96418cf516cdf86286b1b9d9f6ef00f3cd8888daf66016184b5be64c7a2472f84af9ad9390f2dc40d976",
          "sha256": "e286b8e1114a10270d4db93df0252b57ba26eefd84d4f237dcf47f44908845b5",
          "sha1": "3b705f645a383bfbe5c1a1e7780d45c3628f2e32",
          "md5": "ed1328a1b54dc1d5c358192fc0b15195"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.0.2-sources.jar",
          "url": "cmp-8.0.2-sources.jar",
          "size": 5915,
          "sha512": "c006cec2ca224469fa820156d3b9dbe79045dde44a13e802cac2ba9e65c3c0cb5b9464236189376d896294f899abe72845bc6a0efdb49b19c3803503a621ec21",
          "sha256": "d1808c1d9407ddc638206faa3b51ed5d2f1e4fc0b3eb487bb776cc807dc38f6a",
          "sha1": "fdc560556044efd9c2abf212d4a0bf54d266c86f",
          "md5": "dd28dce618460dc8c9fad673ab3e97c4"
        }
      ]
    }
  ]
}
