{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "confiant",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-0.0.0.aar",
          "url": "confiant-0.0.0.aar",
          "size": 6483,
          "sha512": "1b1117c344a6185737ba628d24e4a13a0c9b439d3df53f4ae16fb2a6a5c314eb7726892742dc62e58239ad919560c747d30eff4432a42c4f85e73ddc5ade289a",
          "sha256": "5b95ab0216ffe4f06e46a7dda1b2e9ca1c0b5d2b4d7b267c75322de44351f1b8",
          "sha1": "75348819091b4964d2d7e08497064aa46e9e5dd2",
          "md5": "68ee92b8033d018681acb671779e63b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-0.0.0.aar",
          "url": "confiant-0.0.0.aar",
          "size": 6483,
          "sha512": "1b1117c344a6185737ba628d24e4a13a0c9b439d3df53f4ae16fb2a6a5c314eb7726892742dc62e58239ad919560c747d30eff4432a42c4f85e73ddc5ade289a",
          "sha256": "5b95ab0216ffe4f06e46a7dda1b2e9ca1c0b5d2b4d7b267c75322de44351f1b8",
          "sha1": "75348819091b4964d2d7e08497064aa46e9e5dd2",
          "md5": "68ee92b8033d018681acb671779e63b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-0.0.0-sources.jar",
          "url": "confiant-0.0.0-sources.jar",
          "size": 2814,
          "sha512": "8039003c42dabe027738e258d23a791ed26f0ba4a6ca2919b6eb673712771be1f2be4dc259be2002fc7e83902f566543c1f205bf9dd133df5705e60482c94d4e",
          "sha256": "48e6514ca0e25f214ffb5f0bc85673c323e2fb7c2e64e13fdaf0703b3130661e",
          "sha1": "895fd0caab4fa82fe3469ca14bae5b6da5830c46",
          "md5": "676cb2e03aa636d3b935effd1cb8ab0f"
        }
      ]
    }
  ]
}
