{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "confiant",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-0.0.0.aar",
          "url": "confiant-0.0.0.aar",
          "size": 6280,
          "sha512": "02382eacbed8291d5f2a8d3788a31201961eb1cff85bab6855ef279d5d7f24c692021f7c38f74b39cd152aa84f6000627f557d0d5114fb1f14875d39d7318706",
          "sha256": "15bb96df575e00b33b9e5286baaa1d78ae367034121fa6ab704005d9bf351c71",
          "sha1": "c767d1af978b13c039dec3952e438e8c8e2fef10",
          "md5": "b248b813c7d7dc744f87e5b8058c7f88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-0.0.0.aar",
          "url": "confiant-0.0.0.aar",
          "size": 6280,
          "sha512": "02382eacbed8291d5f2a8d3788a31201961eb1cff85bab6855ef279d5d7f24c692021f7c38f74b39cd152aa84f6000627f557d0d5114fb1f14875d39d7318706",
          "sha256": "15bb96df575e00b33b9e5286baaa1d78ae367034121fa6ab704005d9bf351c71",
          "sha1": "c767d1af978b13c039dec3952e438e8c8e2fef10",
          "md5": "b248b813c7d7dc744f87e5b8058c7f88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "confiant-0.0.0-sources.jar",
          "url": "confiant-0.0.0-sources.jar",
          "size": 2814,
          "sha512": "e62ccbcb229015b3d3ae95ad5bf830d87744160fa3c30cc259edaf222217fa9b572525a3201b4323dc0b1e935b87a899eafdf2f43f105d7d13fa014e2ac7d220",
          "sha256": "7e391734754cd16d6acbfc888975a503419cd638695b7e53db41be47746b974f",
          "sha1": "e87b3eef098a9c007fd3f6a0f62c6de0b1c15eab",
          "md5": "752c1f283261e4f564bed9464ae65c2e"
        }
      ]
    }
  ]
}
