{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.0.aar",
          "url": "yieldlove-8.3.0.aar",
          "size": 659627,
          "sha512": "2b3dcf4227b7e4e3e5e988f9b66f5d137c4759eaa2806a2dc3b447fe3f91793c8324c3c3de7d9429ec56747f76142092bc22b2a85436aa20a1f9546ffae4c662",
          "sha256": "b611ec5b8b9bc2ce89846c65efae3cc63c11376e7dbe44d5b81af1c7ba7075fe",
          "sha1": "382f2e79d5c03228d3f49645c594efa658bf44f8",
          "md5": "127d92d8695eafaefefb46278ccb7109"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.0.aar",
          "url": "yieldlove-8.3.0.aar",
          "size": 659627,
          "sha512": "2b3dcf4227b7e4e3e5e988f9b66f5d137c4759eaa2806a2dc3b447fe3f91793c8324c3c3de7d9429ec56747f76142092bc22b2a85436aa20a1f9546ffae4c662",
          "sha256": "b611ec5b8b9bc2ce89846c65efae3cc63c11376e7dbe44d5b81af1c7ba7075fe",
          "sha1": "382f2e79d5c03228d3f49645c594efa658bf44f8",
          "md5": "127d92d8695eafaefefb46278ccb7109"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.3.0-sources.jar",
          "url": "yieldlove-8.3.0-sources.jar",
          "size": 161603,
          "sha512": "4ce6a575c813bb92bc365d3d0248fc9a98230ca57b8147d3940dd62a2642bb1efda38e23166f5c2b91292574da72824340d8fd8d71cc2ef8f4a83eb8ce5b5c23",
          "sha256": "b562927685bbdb7c6e11344f2b36e6239574ad658e55d0da59060b4f8ea26018",
          "sha1": "ccdc85c0fde8b17424f58e9def1c88638a037983",
          "md5": "8a8453c23b00dd2cd18d2ec1160ab54f"
        }
      ]
    }
  ]
}
