{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "yieldlove",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.0.aar",
          "url": "yieldlove-8.3.0.aar",
          "size": 657901,
          "sha512": "6ad8d3e3bc0ad53ebf269960f1cea112e10a80106717422d9253411982423969c5f0e3c6c6c79b647580ee3997d3d03fb99cb50896c5d602738a0a450fe02141",
          "sha256": "f3383e6bd9c3d26c78dff673d9bc779df3d7e0738ec24c2f816b953a680c78d4",
          "sha1": "b09a04d85965bf967554c812699c041c99b51392",
          "md5": "9791897f12198ebd895d0a38f1a10f7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk-gam-event-handlers",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "yieldlove-8.3.0.aar",
          "url": "yieldlove-8.3.0.aar",
          "size": 657901,
          "sha512": "6ad8d3e3bc0ad53ebf269960f1cea112e10a80106717422d9253411982423969c5f0e3c6c6c79b647580ee3997d3d03fb99cb50896c5d602738a0a450fe02141",
          "sha256": "f3383e6bd9c3d26c78dff673d9bc779df3d7e0738ec24c2f816b953a680c78d4",
          "sha1": "b09a04d85965bf967554c812699c041c99b51392",
          "md5": "9791897f12198ebd895d0a38f1a10f7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yieldlove-8.3.0-sources.jar",
          "url": "yieldlove-8.3.0-sources.jar",
          "size": 161233,
          "sha512": "4524941162e56dca5132533df3e5c9a69b1b28278c077e2d0356fef03a3a70a1c2357319a55ccd2d1ecc93bf7f64f28c8a47e070a0863b230173531bb6832d47",
          "sha256": "0e79964d0109b372b8f632c7615711aad1398ea459573418fa19c2c69fff4831",
          "sha1": "cea9787a28dc4c86eb5bdd7c4743f189c06cad74",
          "md5": "81c203a17c04507b232236ada7eaabbc"
        }
      ]
    }
  ]
}
