{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.1.aar",
          "url": "cmp-8.2.1.aar",
          "size": 25604,
          "sha512": "87dfe88eac2f918c6328fb8c6fa539e21428a934ead14028fb7d3ed068017f09865e303329a4dc62d217fb24f7a2b375874494971065309193bd30880173706c",
          "sha256": "5c27d3eec41d4519489afe5fcefaa566dcb1b17cc82575a08468c3fce7423d62",
          "sha1": "3b9d49e49218303b0fe459ebc419638878df3a0a",
          "md5": "a219a8097bc9b1dff0934609f4015cf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.1.aar",
          "url": "cmp-8.2.1.aar",
          "size": 25604,
          "sha512": "87dfe88eac2f918c6328fb8c6fa539e21428a934ead14028fb7d3ed068017f09865e303329a4dc62d217fb24f7a2b375874494971065309193bd30880173706c",
          "sha256": "5c27d3eec41d4519489afe5fcefaa566dcb1b17cc82575a08468c3fce7423d62",
          "sha1": "3b9d49e49218303b0fe459ebc419638878df3a0a",
          "md5": "a219a8097bc9b1dff0934609f4015cf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.2.1-sources.jar",
          "url": "cmp-8.2.1-sources.jar",
          "size": 5713,
          "sha512": "98b9b01af0f668ea529796811ba4bb3e8ca85f19fd21a838ab750c80d8213e56f20d40ed3a8ee8a8172f6d52121b019c81746ed1cbc288aeff43b4ef0d6796a7",
          "sha256": "6ea33e2457f9c345c72a431afdc6dfb921df19fa108047733f6f7dd0be2ac371",
          "sha1": "c138284330777f0507111ab710eaad7f19e7c4c9",
          "md5": "273ee271e71069d30263c6a6c2d93720"
        }
      ]
    }
  ]
}
