{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yieldlove.adIntegration",
    "module": "cmp",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.1.aar",
          "url": "cmp-8.2.1.aar",
          "size": 25641,
          "sha512": "3722b3518d96b0444768ea083dbe2a1bd6ffb1e35da0c2c986ce49cc6331373d7f2884d6b52f71bb4c7a039db5aff9a5314286551de29fc1099d3b9f28dd5210",
          "sha256": "d25dae7ffe7bf3df050760ddfc02e118ce28b705247902df6308015394fded30",
          "sha1": "9ad5f19489bfe45699c1c3e236b9c160c50c78f1",
          "md5": "8d6578d8e784a1182d7ff30461c53141"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.yieldlove.adIntegration",
          "module": "yieldlove",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.11"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-8.2.1.aar",
          "url": "cmp-8.2.1.aar",
          "size": 25641,
          "sha512": "3722b3518d96b0444768ea083dbe2a1bd6ffb1e35da0c2c986ce49cc6331373d7f2884d6b52f71bb4c7a039db5aff9a5314286551de29fc1099d3b9f28dd5210",
          "sha256": "d25dae7ffe7bf3df050760ddfc02e118ce28b705247902df6308015394fded30",
          "sha1": "9ad5f19489bfe45699c1c3e236b9c160c50c78f1",
          "md5": "8d6578d8e784a1182d7ff30461c53141"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cmp-8.2.1-sources.jar",
          "url": "cmp-8.2.1-sources.jar",
          "size": 5712,
          "sha512": "cf0a595e29361c76074dd5b781c046e17f93e5db56d59fcf4e00486f1a1fcde671c02c3f72aa4c6a4ad2317a563971f96bee3089422589324e8df38f29957811",
          "sha256": "81edbb238a7a25102ddc3f4cff0f0309d4dfaf53ba6435188d9b9ff7f78f361a",
          "sha1": "05faac77d06313bd309863d4358a531ecac7ac4f",
          "md5": "fc0b5c3b0bb785e8458f8e50ec063c56"
        }
      ]
    }
  ]
}
